### ISSUE TITLE
context manager for PySide2 and PyQt5 in tests

### ISSUE THREAD

**Issue by hdd** [mottosso/Qt.py#100]
Hi , is there any reason why there isn't a context manager for these two binding ?
Is anyone already looking on adding them ?
Asking as it would allow a more thoughtful testing.
Cheers.
L.

**Comment by mottosso** [comment]
Yes, it's because they aren't currently available in test runners; Travis, AppVeyor and Docker. There is a separate issue about including these, you are welcome to have a look at including support for this, at which point we can include these context managers.

**Comment by fredrikaverpil** [comment]
> There is a separate issue about including these
https://github.com/mottosso/Qt.py/issues/93

**Comment by hdd** [comment]
Cheers.
