### ISSUE TITLE
code structure reorganisation proposal

### ISSUE THREAD

**Issue by hdd** [mottosso/Qt.py#101]
After having spent some time trying to get around the various differences in the framework, has become pretty clear to me, that all these in place replacements (still many to come I fear), might bring soon the code to a point where is going to be hard to maintain, especially if many other contributors are coming in.

Here an idea on how the code could be reorganised :

```
├── docs
│   └── source
├── setup.py
├── source
│   └── Qt
│       ├── __init__.py
│       └── bindings
│           ├── __init__.py
│           ├── _pyqt4_.py
│           ├── _pyqt5_.py
│           ├── _pyside2_.py
│           └── _pyside_.py
└── tests
    ├── test_pyside2.py
    ├── test_pyside.py
    ├── test_qt4.py
    └── test_qt5.py
```

Any thought on this ?
Cheers.

**Comment by fredrikaverpil** [comment]
Hm. Do we really need to extract the entire bindings like that?

I'm thinking there's going to be a lot of simple remappings and then we're going to add classes and functions to support remappings. I think it could be valuable to have all remappings in its own file for overview purposes. Then make custom classes etc into submodules.

```
├── docs
│   └── source
├── setup.py
├── source
│   └── Qt
│       ├── __init__.py
│       └── lib
│           ├── __init__.py
│           ├── loadUi_.py
│           ├── custom1_.py
│           └── custom2_.py
└── tests
    ├── test_pyside2.py
    ├── test_pyside.py
    ├── test_qt4.py
    └── test_qt5.py
```

But as a whole, I think it's probably inevitable that we need to split Qt.py up into pieces at some point.

**Comment by hdd** [comment]
Yeap, same here, soon or later it'll have to happen so I think is better look into it asap.

The idea of splitting the binding is my main point for the restructure, so we can have dedicated modules for each one, and we can keep any patch/fix scoped properly. Could this be leading to some code duplication ? Sure, there's the risk, but the feeling is that it'll bring more benefits than problems.

**Comment by mottosso** [comment]
Thanks for bringing this up, it was bound to be discussed at some point and its a healthy discussion to have. Both now and for the future.

But before this train of though travels any further, I'll say; no. This isn't a direction I'm interested in taking this project.

This will instead be what separates Qt.py from other project of similar goals, the driving motivation being dead simple adoption, use and maintenance.

I think that as a project becomes larger, it does makes sense to separate functionality out into additional modules, but it also opens up the door to bloat. And frankly there isn't enough differences between the bindings to justify a Python package of modules.

Case in point, the ongoing isse on adding additional argumentns tom`load_ui`. This function went from a few lines of code to tens if not a hundred in the hunt for 1-1 correspondance with PyQt. The entire codebase and test suite doubled in size for a small speck of a feature used by a minority of users. What i would rather see happen is that we implement the similaritirs and offer best practices on how to achieve similar results in a cross-compatible way without resorting to re-implementing feature from one binding to another.

At the moment, installing and using Qt.py is a matter of copying the contents of the one module and pasting this into your new project. Installers, pip and environment variables are all optional and understanding the code is dead simple. I'd like to keep it this way and instead suggest contributions to the README on how to develop code that works across bindings. Alternative routes, in place of warpping functionality.

**Comment by mottosso** [comment]
This, this is the one we should fill up with alternative routes through binding differences.

- [`CAVEATS.md`](https://github.com/mottosso/Qt.py/blob/master/CAVEATS.md)

How about this; when there is no possible alternative to a binding difference, only them do we have a look at implementing something custom?

At the end of thue day, I would much rather see software developed with cross-compatibility in mind, than software relying on a shim for missing functionality. I think that perhaps that the critical point what should end up separating Qt.py from its neighbours.

CAVEATS.md is an excellent place to document these differences. It is both human readable, and automatically tested. The automatic tests will help ensure consistency in each paragraph. It would be trivial to implement a minimal search engine or in-app tooltip or linter for e.g. Sublime based on this for developers to stay up to date with potential dangers.

**Comment by fredrikaverpil** [comment]
> the driving motivation being dead simple adoption, use and maintenance.

:+1: 

> I would much rather see software developed with cross-compatibility in mind, than software relying on a shim for missing functionality.

I couldn't agree more. This is a big one.

**Comment by hdd** [comment]
>> This isn't a direction I'm interested in taking this project.
Then I guess this ticket can be closed  for good, as it was all about restructuring the code :)

**Comment by mottosso** [comment]
Glad you agree. :)

**Comment by fredrikaverpil** [comment]
How about we define what came out of this issue somewhere in the README, preferably under the developer guide?
