### ISSUE TITLE
Warn users about Qt.py-only functionality

### ISSUE THREAD

**Issue by hdd** [mottosso/Qt.py#109]
As a user and developer I would like to be notified when using backward or forward compatibility  methods when using them.

**Comment by hdd** [comment]
Worth using python warning system , https://docs.python.org/2/library/warnings.html
so we can filter them through the logging system as well.

**Comment by mottosso** [comment]
Thanks @hdd.

I agree this would be good and I've got in mind one way of achieving this, but it comes at a cost. The cost is likely too high, so I'm interested in alternative ways of achieving this result.

#### The idea

The inherent problem of triggering anything when accessing a member variable, such as `QtWidgets.QWidget` versus `QtGui.QWidget` is that there isn't any code inbetween asking for this member and getting it.

The idea is to convert `QtWidgets` from being a module into being an object and override `__getattr__` such that asking for a member would allow us to trigger these warnings.

```python
class QtWidgets(object):
  def __getattr__(self, attr):
    warnings.warn("Not backwards compatible!")
    return getattr(PyQt5.QtWidgets, attr)

Qt.QtWidgets = QtWidgets()
```

I'm a bit weary however of doing this, as we would move away from wrapping a module - e.g. `PySide.QtGui` - with another module to wrapping it with a class, possibly and most likely breaking all sorts of things.

#### Alternative

So, what's another way of achieving this?

**Comment by hdd** [comment]
agree that would be the ideal way of doing it , but I found issues on wrapping the classes and replace them in place as you are describing. Especially when you retrieve the class from another instance and not from the top module (Qt).  Using unbounded methods (function patching) seems to be working fine so far. 

I would suggest to keep going with unbound methods for the time being, while looking into a proper way to have the full widget/object class patched with bound methods, so users can use and test the module and implementation in the meanwhile.

**Comment by mottosso** [comment]
> Using unbounded methods (function patching) seems to be working fine so far. 

Could you show an example of this?

**Comment by hdd** [comment]
You can see this in use on #98 where I patch the translate function as well as in #96 for the headers.
This allow you to retrieve the header from the instanced object and access the patched method.
These patched methods results to be unbounded.

**Comment by mottosso** [comment]
Sure, that shouldn't be a problem.

Did you not also want warnings when users try and use, e.g. `QtGui.QWidget` when they should have used `QtWidgets.QWidget`? Or was it strictly related to direct function calls?

**Comment by hdd** [comment]
If we assume all the bindings will be mirroring the PySide2/Qt5 implementation , guess is not needed...
but I'm up for chatting about it. (just trying to avoid to bloat the shell with too many info, which are distracting)

I think is more important to notify the users when they try to use/access something is not supposed to be there in the implementation they are using.

**Comment by mottosso** [comment]
> I think is more important to notify the users when they try to use/access something is not supposed to be there in the implementation they are using.

Yeah, I think that could be helpful too. I'm just not sure how to technically achieve this..

Perhaps some form of external linting process?

```bash
$ python -m Qt.py --check my_module.py
my_module.py:L54: QtGui.QWidget should be QtWidgets.QWidget
my_module.py:L107: QtCore.pyqtSignal should be QtCore.Signal
...
```

If it aligns with how other linters output their warnings, maybe something along those lines could later be integrated with native linters, like Sublime-Linter and such.

**Comment by hdd** [comment]
I'm more thinking of providing warnings from within the patched methods:

```
import warnings

def myPatchedMethod(*args, **kwargs):
         warnings.warn(
        "shouldn't use this function anymore! Now use XYZ.",
        DeprecationWarning
    )
      return something(*args, **kwargs) 

```

**Comment by mottosso** [comment]
Ah, ok. Which functions should we add this warning too? Do you mean when we choose to upgrade and deprecate our own functionality?

I think we might be talking of different things. Maybe if you could show a few examples or produce a PR with your idea we'd be able to progress faster.

**Comment by hdd** [comment]
I think this should be in each function we patch, wither forward or backward.
Is not about deprecating functionalities (that's why I was suggesting of coming up with custom warning), but more about letting the user know, he's not using the original API , but a wrapped function, which we have added to leverage the differences.

I agree, from what I understand you are looking on providing something py2to3, which analise the code, and report how things should be changed.

What I'm thinking about is just a way to notify the users when they access a method which is really not part of the original implementation (think of the setResizeMode vs setSectionResizeMode in QHeaders).

So for example if someone is using pyside , but on a legacy code which still use pyside2 (eg in Maya), this should be notifying that the function he's using is a patched one.

**Comment by mottosso** [comment]
> he's not using the original API , but a wrapped function

Ahaaaa, ok, so this was what I didn't understand.

You want a warning when using *any* function that isn't in the original binding? Ok. I'm not sure I agree with this. In that case, I'd rather see a namespace for it.

```python
import Qt
Qt.my_custom_functionality.load_ui()
```

At the moment, custom functionality is mixed with native so you don't know what you're using. Maybe that's the problem?

Personally, I'm not sure it matters. But I can see what you mean and it's worth having a conversation about.

**Comment by hdd** [comment]
>> At the moment, custom functionality is mixed with native so you don't know what you're using. Maybe that's the problem?

Yup, that's exactly the issue I'm trying to solve with this.
If not solving, at least, having the users aware of what they are actually using.

I would set the logging to warning to a lever which doesn't print anything by default.
In case , this can be set to print out all these info, which could help porting code, and understand differences.

**Comment by mottosso** [comment]
Solved via documentation.

- https://github.com/mottosso/Qt.py#documentation
