### ISSUE TITLE
Add QAbstractProxyModel to PySide2

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt.py#127]
This class is misplaced in `QtGui` when it [should be](https://doc.qt.io/qt-5/qabstractproxymodel.html) in `QtCore`.

**Comment by mkolar** [comment]
Actually it seems that it's correctly placed in the QtCore. I don't know why it seemed missing at first, but I've double checked now and it's correct I believe.

**Comment by mottosso** [comment]
Ah yes, I also double checked. Found that I had tried using `PySide` instead of `PySide2`, where it is misplaced. In PySide2 it does look right.
