### ISSUE TITLE
IDE autocompletion

### ISSUE THREAD

**Issue by sebastianelsner** [mottosso/Qt.py#128]
I am using Eclipse + PyDev and had a look at Qt.py. I am wondering, how do you get autocompletion for Qt.py in your editors. Does it just work for you? PyDev does not seem to be too smart when using Qt.py

**Comment by mottosso** [comment]
Hi @sebastianelsner, thanks for reporting this!

I'm not using any autocompletion myself so I haven't had the pleasure of encountering this problem.

The one thing that might throw an autocompleter off, is how the module `Qt.py` is being replaced by the original binding, like this.

```python
import sys
import PyQt5

sys.modules["Qt"] = PyQt5
```

It's possible your autocompleter performs black magic based on this detail, and that doing this breaks it.

Does autocompletion work for you with the original binding? That is, without Qt.py?

**Comment by fredrikaverpil** [comment]
> Does it just work for you?

For me, it just works. I'm using Sublime Text 3 with flake8.
Do you know which linter you're using?

**Comment by fredrikaverpil** [comment]
Ah, sorry... you're talking about auto completion. I'm just using Jedi in Sublime Text for auto completion and I see it doesn't work for Qt.py.

**Comment by mottosso** [comment]
Let's see if we can fix this.

How can we setup a reproducible example? Ideally as a unit test.

**Comment by fredrikaverpil** [comment]
I see Jedi doesn't autocomplete PySide/PyQt. After having installed [PyQt5 Completions](https://packagecontrol.io/packages/PyQt5%20Completions) I now get autocompletion with Qt.py:

![autocompl](https://cloud.githubusercontent.com/assets/994357/18169831/2f45fc52-705c-11e6-8047-2f84a5eb3872.png)

**Comment by sebastianelsner** [comment]
Yes, autocompletion did work with PyQt4. Good to know jedi does not understand this as well. Afaik PyDev has its own implementation for completion, so I don't think we can come up with a "real" test. 
The plugin you installed is basically a "predefinition".  I think I may resort to that, too. PyDev supports the ".pypredef" file syntax.

**Comment by mottosso** [comment]
Ah, I see. It may be that PyDev is triggering this autocompletion at the sight of "PyQt4" amongst the imported modules. It might need to recognise "Qt" as a trigger for this.

Maybe worth filing a ticket with PyDev to get Qt.py in there.

**Comment by fredrikaverpil** [comment]
Perhaps this issue shouldn't be marked as a bug?

**Comment by mottosso** [comment]
Yeah, no, this looks to be out of band for this project.
