### ISSUE TITLE
Address import syntax limitations

### ISSUE THREAD

**Issue by zslane** [mottosso/Qt.py#133]
The following will fail in an environment where Qt binds to PySide or PyQt4:

`from Qt.QtWidgets import QPushButton`

I feel that either the shim should be enhanced to handle this common import syntax, or this failure mode should be documented in CAVEATS.md (and anywhere else users might look for known problems).

**Comment by mottosso** [comment]
Thanks for reporting this @zslane.

Can you think of any reason why this might be happening, and how we could repair it?

**Comment by mottosso** [comment]
Ok, I've got a potential fix that needs some testing.

Save this file, and run:

```bash
$ cd Qt.py
$ git apply fix_133.patch
```

**fix_133.patch**

```bash
From 31f411187a177f17d08cd84c8de5c1ec9999e16c Mon Sep 17 00:00:00 2001
From: Marcus Ottosson <marcus@abstractfactory.io>
Date: Thu, 8 Sep 2016 08:42:21 +0000
Subject: [PATCH] Fix #133

---
 Qt.py | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/Qt.py b/Qt.py
index 69f1ff5..ac61291 100644
--- a/Qt.py
+++ b/Qt.py
@@ -129,6 +129,9 @@ def pyqt4():
     remap(QtCore, "QSortFilterProxyModel", QtGui.QSortFilterProxyModel)
     remap(QtCore, "QAbstractProxyModel", QtGui.QAbstractProxyModel)
 
+    # Patch #133
+    sys.modules[__name__ + ".QtWidgets"] = QtGui
+
     try:
         from PyQt4 import QtWebKit
         remap(PyQt4, "QtWebKitWidgets", QtWebKit)
@@ -177,6 +180,9 @@ def pyside():
     remap(QtCore, "QItemSelectionModel", QtGui.QItemSelectionModel)
     remap(QtCore, "QAbstractProxyModel", QtGui.QAbstractProxyModel)
 
+    # Patch #133
+    sys.modules[__name__ + ".QtWidgets"] = QtGui
+
     try:
         from PySide import QtWebKit
         remap(PySide, "QtWebKitWidgets", QtWebKit)
-- 
1.9.1
```

Le me know if that works for you and I'll have a think about how to make it safe.

**Comment by zslane** [comment]
Yes, that works like a charm. Thanks!

**Comment by mottosso** [comment]
[Released](https://github.com/mottosso/Qt.py/releases/tag/0.4.1) and uploaded to PyPI as 0.4.1
