### ISSUE TITLE
QtCore.QSortFilterProxyModel missing for PyQt4

### ISSUE THREAD

**Issue by tokejepsen** [mottosso/Qt.py#144]
## Description

Using PyQt4 the ```QtCore.QSortFilterProxyModel``` attribute is missing.

## Expected results

Would assume the attribute to be the same for PyQt4 and PySide.

## Short reproducible

Have PyQt4 installed and run this ```QtCore.QSortFilterProxyModel```.

**Comment by mottosso** [comment]
What version are you on?

```python
import Qt
print(Qt.__wrapper_version__)
```

**Comment by tokejepsen** [comment]
Using ```0.6.0```

**Comment by mottosso** [comment]
Hm, I can't seem to reproduce this.

```python
>>> import Qt
>>> from Qt import QtCore
>>> QtCore.QSortFilterProxyModel
<class 'PyQt4.QtGui.QSortFilterProxyModel'>
>>> Qt.__wrapper_version__
'0.6.0'
```

It's remapped here:

- [https://github.com/mottosso/Qt.py/blob/master/Qt.py#L168](https://github.com/mottosso/Qt.py/blob/3d4c6b52b684530564f7abfa2fabea2325d85a06/Qt.py)

And was solved here:

- https://github.com/mottosso/Qt.py/commit/26116cc7eba24e5b099eec3e2c91705473f6f217

**Comment by tokejepsen** [comment]
Sorry about this, it was my environment that was messed up and not getting the correct PyQt4.
