### ISSUE TITLE
QtCompat to QtSix

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt.py#145]
### Goal

Highlight similarities between the Python library `six` for compatibility between Python 2 and 3 by calling the compatibility module `QtSix`.

```python
from Qt import QtSix
QtSix.QString()
QtSix.setSectionResizeMode()
```

**Comment by fredrikaverpil** [comment]
I'm not sure I follow. There are no stuff related to Qt in six, are there?

**Comment by mottosso** [comment]
[`six`](https://pythonhosted.org/six/) is to Python 2 and 3 what Qt.py is to Qt 4 and 5.

The idea would be to call it `QtSix` so as to highlight this similarity. Those that have worked with `six` could map their existing understanding to what `QtSix` is for.

`QtCompat` makes sense due to the use of "compat" for "compatibility", whereas `QtSix` makes sense due to association with `six`.

I'm not confident it's any better, I mostly just wanted the idea on paper so as to speak about it and have a record of the decision being made.

What do you think?

**Comment by BigRoy** [comment]
I think the similarity is nice, but overall it doesn't feel like an improvement. It just doesn't instantly ring a bell, where QtCompat brings across the overall intentions.

I'd personally vote for QtCompat.

**Comment by fredrikaverpil** [comment]
+1 for QtCompat just because QtSix feels like it has some connection with six. I didn't at all understand what you initially meant. :)

**Comment by mottosso** [comment]
Fair enough. `QtCompat` it is. :)
