### ISSUE TITLE
QtCompat translate.

### ISSUE THREAD

**Issue by BoubQC** [mottosso/Qt.py#148]
Hey guys, it's me again.

Think there's a bug when adding the translate function to QtCompat.

`_add(PySide2, "translate", lambda context, sourceText, disambiguation, n: (
        QtCore.QCoreApplication(context, sourceText,
                                disambiguation, None, n)))`

It should be 'QtCore.QCoreApplication.translate' right? Missing the translate...

If I change it I get an argument type error and I haven't dug into that...

Thanks for your time.

**Comment by mottosso** [comment]
Yes, you ar right. It's really great you are pointing these things out; the `--convert` feature is in Alpha and will change and improve on exactly this type of feedback.

This looks like a typo to me; fixing it would be a matter of changing `QtCore.QCoreApplication...` to `QtCore.QCoreApplication.translate...`.

I would be very happy to see a Pull request from you that fixes this, but let me know if you'd rather someone else does it and I'll make it happen.

Thanks again!

**Comment by BoubQC** [comment]
@mottosso At the time I cannot do a pull request since I get a an argument type error when adding '.translate'.

Didn't have any time to fix it yet on my side.

**Comment by BoubQC** [comment]
@mottosso Got something going on. I'm not setuped to run your tests so could you test it for me? If no I'll test it later this week.

Working in maya 2015 and 2017 (Pyside and Pyside2) Haven't tested it on PyQt4 or 5.

Would need someone to validate QCoreApplication::Encoding::CodecForTr is good. And if we need it for PyQt4.

https://github.com/BoubQC/Qt.py/commit/4435e55d2153a0077391d1563b46a8fb35b6a0be

**Comment by mottosso** [comment]
That sounds great! When you make a pull-request, GitHub will run the tests for us and tell you of the results. It will do that for every commit you push to your fork.
