### ISSUE TITLE
PySide2 ImportError: cannot import name 'QtUiTools'

### ISSUE THREAD

**Issue by willjp** [mottosso/Qt.py#149]
Hey Guys!

I've noticed some inconsistencies between Maya's PySide2 and the latest PySide2 that prevent it from being used in Qt.py:

* The latest version of https://codereview.qt-project.org/pyside/pyside-setup does not include `QtUiTools` in it's ``__init__.py``
* Within Maya2017 `PySide2` still includes the `QtUiTools` module.
* `Qt5` does not list the module here: http://doc.qt.io/qt-5/qtmodules.html
* (`Qt4` does: http://doc.qt.io/qt-4.8/modules.html)

It looks like the module has been replaced with QFormBuilder in Qt5 (But I've never actually used a .ui file, so I could be horribly incorrect here): 
http://doc.qt.io/qt-5/qformbuilder.html
http://stackoverflow.com/questions/20670457/qt-5-unknown-modules-in-qt-uitools

If it has been replaced, you might need a version check in the `_pyside2` function to determine whether or not it should be imported.

**Comment by mottosso** [comment]
Thanks for your diligent documenting of this issue! This sure does sound suspicious.

Would it be possible to tell us a bit about how you noticed it, and/or the kind of problems it causes? That would help us better understand the context within which it is being repaired.

**Comment by fredrikaverpil** [comment]
Yes, thank you @willjp this is strange. I'll try to see if Autodesk manually patched PySide2 for this.

**Comment by fredrikaverpil** [comment]
@willjp did you build PySide2 and give it a try recently?

I'm using a [macOS wheel built 11 days ago](https://bintray.com/fredrikaverpil/pyside2-wheels/pyside2#files/osx10.9.5) and with it I can import QtUiTools just fine:

```python
Python 3.5.1 (default, Apr 18 2016, 11:46:32) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PySide2
>>> from PySide2 import QtUiTools
>>> print(QtUiTools)
<module 'PySide2.QtUiTools' from '/usr/local/lib/python3.5/site-packages/PySide2/QtUiTools.so'>
```

You can find the build details in [this git repo](https://github.com/fredrikaverpil/pyside2-wheels) and the resulting wheels are hosted [here in BinTray](https://bintray.com/fredrikaverpil/pyside2-wheels/pyside2#files/).

**Comment by fredrikaverpil** [comment]
Regarding the Qt5 docs, if you scroll down a bit on the [modules list page](http://doc.qt.io/qt-5/qtmodules.html) you'll find QtUiTools as "Qt UI Tools":

![screen shot 2016-10-19 at 08 41 10](https://cloud.githubusercontent.com/assets/994357/19508156/df5d13e6-95d7-11e6-91d6-9f4ec8b361d0.png)

**Comment by willjp** [comment]
Wow! You guys are fast. I'll give you some more info as soon as I finish work tonight. I'm sorry to keep you waiting!

**Comment by fredrikaverpil** [comment]
@willjp there's no hurry, take your time. :)

**Comment by willjp** [comment]
@fredrikaverpil , you're absolutely right. I did a searched the Qt4 then Qt5 page, but did not account for the space between 'Qt' and 'Ui Tools'. Sorry, that I misled you guys! If this is the case, I'm wondering if it is possibly an issue with the latest `PySide2` commit?
<br>
<br>


I just recompiled PySide2 now (in a fresh docker container), the issue persists, and I have a few more details for you guys. The environment is:
* ''Operating System'': Ubuntu:16.04
* ''Python'': python3.5

``` bash
export QT_PREFERRED_BINDING=PySide2
python3 -c "import Qt"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/Qt.py", line 393, in <module>
    cli(sys.argv[1:]) if __name__ == "__main__" else init()
  File "/usr/local/lib/python3.5/dist-packages/Qt.py", line 366, in init
    raise ImportError("No Qt binding were found.")
ImportError: No Qt binding were found.
```

The cause of the error is coming from here:
``` python
#### /usr/local/lib/python3.5/dist-packages/Qt.py
def _pyside2():
    import PySide2
    from PySide2 import QtGui, QtWidgets, QtCore, QtUiTools
    ...
```

And the real source of the problem seems to be here:
``` python
#### /usr/local/lib/python3.5/dist-packages/PySide2/__init__.py
__all__ = ['QtCore', 'QtGui', 'QtNetwork', 'QtOpenGL', 'QtSql', 'QtSvg', 'QtTest', 'QtWebKit', 'QtScript']

# (no QtUiTools module)
```

And then just to be really thorough, this is the dockerfile I'm using (many thanks to @fredrikaverpil , this will look very familiar :) )

``` 
FROM ubuntu:16.04

# ===========
# Base System
# ===========

RUN apt-get update
RUN apt-get install -y sudo zsh tmux vim


# =============
# Build PySide2
# =============

RUN apt-get install -y   python3  python3-pip  python3-dev  python3-pyside
RUN python3 -m pip install wheel
RUN python3 -m pip install ipython
RUN python3 -m pip install ipdb
RUN python3 -m pip install Qt.py


RUN apt-get update && apt-get install -y \
                      python3-pip python3-dev \
                      build-essential git cmake libxml2 libxslt1.1 libxml2-dev libxslt1-dev \
                      qt5-default qtbase5-dev \
                      qttools5-dev-tools libqt5clucene5 libqt5concurrent5 libqt5core5a libqt5dbus5 libqt5designer5 libqt5designercomponents5 libqt5feedback5 libqt5gui5 libqt5help5 libqt5multimedia5 libqt5network5 libqt5opengl5 libqt5opengl5-dev libqt5organizer5 libqt5positioning5 libqt5printsupport5 libqt5qml5 libqt5quick5 libqt5quickwidgets5 libqt5script5 libqt5scripttools5 libqt5sql5 libqt5sql5-sqlite libqt5svg5 libqt5test5 libqt5webkit5 libqt5widgets5 libqt5xml5 libqt5xmlpatterns5 libqt5xmlpatterns5-dev

RUN git clone --recursive https://codereview.qt-project.org/pyside/pyside-setup

RUN python3 \
       pyside-setup/setup.py \
       bdist_wheel \
       --ignore-git \
       --qmake=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake \
       --cmake=/usr/bin/cmake

RUN pip3 install pyside-setup/dist/*.whl
```

Also, I know you guys are looking at a lot of OS's here, so to avoid a false positive I noticed the the ubuntu:16.04 image includes the original PySide, which gets used in PySide2's place by default without the `QT_PREFERRED_BINDING` environment variable being set.


Just running over to my sister's for dinner, but I'll be back later! Thanks for being super friendly guys :)

**Comment by fredrikaverpil** [comment]
Hi again @willjp and thanks for this excellent report.

So, I've found what's causing this. During the build phase:

```
CMake Warning at CMakeLists.txt:251 (find_package):
  By not providing "FindQt5UiTools.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5UiTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5UiTools" with
  any of the following names:

    Qt5UiToolsConfig.cmake
    qt5uitools-config.cmake

  Add the installation prefix of "Qt5UiTools" to CMAKE_PREFIX_PATH or set
  "Qt5UiTools_DIR" to a directory containing one of the above files.  If
  "Qt5UiTools" provides a separate development package or SDK, be sure it has
  been installed.
```

This can be more closely inspected in the [Ubuntu 16.04 Travis-CI build on line 2529](https://travis-ci.org/fredrikaverpil/pyside2-wheels/jobs/166011665#L2529).

This is actually something I've seen happen on other Linux distributions and I now realize I've even filed a bug report about it here: https://bugreports.qt.io/browse/PYSIDE-343

I stumbled upon a different although probably related [issue](https://bugreports.qt.io/browse/PYSIDE-342) in CentOS 7 where I was suggested to try out [a hack](https://github.com/fredrikaverpil/pyside2-wheels/blob/dcac29afa995a571e72efc5a2c0e919c76b5691c/Dockerfile-centos7-py3.5#L15-L35) and which turned out to work for that issue. And when building PySide2 in CentOS 7 the QtUiTools module is found just as expected during build time. So, I wonder if maybe this comes down to the same things; tweaking the CMakeLists.txt to make CMake find the modules in Ubuntu.

But so, this issue is not related to Qt.py and more of an issue related to the [pyside2-wheels](https://github.com/fredrikaverpil/pyside2-wheels) project, where I now see I actually have created [an issue](https://github.com/fredrikaverpil/pyside2-wheels/issues/4) for this very problem already. My memory really seems to be failing me on this one, sorry. :)
I don't use Ubuntu myself so I guess that is why I haven't put any effort into trying to solve this.

I propose we try to solve this in the pyside2-wheels project because there we can experiment and make pull requests and have Travis-CI build PySide2 for us.

**Comment by mottosso** [comment]
> I propose we try to solve this in the pyside2-wheels project because there we can experiment and make pull requests and have Travis-CI build PySide2 for us.

That's fine by me. Are we sure though that this module is a requirement of PySide, and not optional and part of something like [PySide-Tools project](https://github.com/PySide/pyside2-tools)? If it is, it might be worth making it optional in Qt.py too.

**Comment by fredrikaverpil** [comment]
Yes, I'm 100% sure. On all other platforms in the pyside2-wheels project, the QtUiTools module is included and works right out of the box with the built wheels and Qt.py without any modifications to the build scripts.

The pyside2-wheels aim to only create vanilla flavoured wheels.

This is not like the pyside2-tools project.

**Comment by mottosso** [comment]
Perfect, thanks for clarifying!

**Comment by fredrikaverpil** [comment]
Sure, no problem :)

There are in fact loads of those CMakeLists.txt errors I posted above when you build on Ubuntu 16.04. Here's a more brief list of those modules:

```
module Qt5Core found
module Qt5Concurrent found
module Qt5Gui found
module Qt5Widgets found
module Qt5PrintSupport found
-- optional module Qt5Svg skipped
-- optional module Qt5Designer skipped
-- optional module Qt5UiTools skipped
-- optional module Qt5WebKit skipped
-- optional module Qt5WebKitWidgets skipped
-- optional module Qt5Script skipped
-- optional module Qt5ScriptTools skipped
-- optional module Qt5Help skipped
-- optional module Qt5Multimedia skipped
-- optional module Qt5Quick skipped
-- optional module Qt5Qml skipped
-- optional module Qt5QuickWidgets skipped
-- optional module Qt5WebEngineWidgets skipped
-- optional module Qt5WebChannel skipped
-- optional module Qt5WebSockets skipped
-- optional module Qt5X11Extras skipped
module Qt5Xml found
module Qt5XmlPatterns found
module Qt5PrintSupport found
module Qt5Sql found
module Qt5Test found
module Qt5Network found
```

Please note, the fact that it says "optional" just means you *can* build PySide2 without them if you wish. But they're part of the standard build.

I know that on all platforms the `Qt5WebEngineWidgets` module is not found and skipped... but that's due to the fact that it's not ready yet I believe.

So this type of build summary is what's considered "normal", at least at this stage, since PySide2 hasn't really been released yet:

```
module Qt5Core found
module Qt5Concurrent found
module Qt5Gui found
module Qt5Widgets found
module Qt5PrintSupport found
module Qt5Xml found
module Qt5XmlPatterns found
module Qt5Svg found
module Qt5PrintSupport found
module Qt5Sql found
module Qt5Designer found
module Qt5UiTools found
module Qt5Test found
module Qt5Network found
module Qt5WebKit found
module Qt5WebKitWidgets found
module Qt5Script found
module Qt5ScriptTools found
module Qt5Help found
module Qt5Multimedia found
module Qt5Quick found
module Qt5Qml found
module Qt5QuickWidgets found
-- optional module Qt5WebEngineWidgets skipped
module Qt5WebChannel found
module Qt5WebSockets found
module Qt5X11Extras found
-- Checking for QAbstractPrintDialog in Qt5Widgets -- not found
-- Checking for QGtkStyle in Qt5Widgets -- not found
-- Checking for QPageSetupDialog in Qt5Widgets -- not found
-- Checking for QPrintDialog in Qt5Widgets -- not found
-- Checking for QPrintEngine in Qt5Widgets -- not found
-- Checking for QPrintPreviewDialog in Qt5Widgets -- not found
-- Checking for QPrintPreviewWidget in Qt5Widgets -- not found
-- Checking for QPrinter in Qt5Widgets -- not found
-- Checking for QPrinterInfo in Qt5Widgets -- not found
-- Checking for QSessionManager in Qt5Widgets -- not found
-- Checking for QSizeGrip in Qt5Widgets -- not found
-- Checking for QSystemTrayIcon in Qt5Widgets -- not found
-- Checking for QMacStyle in Qt5Widgets -- not found
-- Checking for QSslCertificate in QtNetwork -- not found
-- Checking for QSslCipher in QtNetwork -- not found
-- Checking for QSslConfiguration in QtNetwork -- not found
-- Checking for QSslError in QtNetwork -- not found
-- Checking for QSslKey in QtNetwork -- not found
-- Checking for QSslSocket in QtNetwork -- not found
-- QT_SRC_DIR variable not set or graphviz not found, apidoc generation targets disabled.
-- Configuring done
-- Generating done
```

**Comment by mottosso** [comment]
Just want to say, it's so great that you are this thorough with your research and well spoken in your presentation. Do keep that up!

**Comment by fredrikaverpil** [comment]
Hm actually... no. I'm now seeing discrepancies in the module list on my different Travis builds. I need to investigate...

> Just want to say, it's so great that you are this thorough with your research and well spoken in your presentation. Do keep that up!

Thanks :)

**Comment by fredrikaverpil** [comment]
Allright, I updated [the README](https://github.com/fredrikaverpil/pyside2-wheels) over at the pyside2-wheels project to reflect which modules are in fact being skipped and are missing.

To sum it up, it seems to be a djungle of package issues on all platforms. Some modules found on some platforms and then not found on some other platforms... where Ubuntu 16.04 is in the worst state.

Unfortunately, I don't have the time to investigate further and try to fix this at this point in time. I hope The Qt Company will eventually address these things.

**Comment by willjp** [comment]
Thanks very much @fredrikaverpil! I'd help if I thought I could, but I'm still pretty new to cpp. Debugging the Qt project probably isn't the best starting point haha :). I'm closing the issue (this has nothing to do with Qt.py) and I'll use a CentOS base in the meantime. Gotta love docker.

Thank you both so much :)

**Comment by Kthulhu** [comment]
Hey guys, sorry for reopening this, but I googled this page, having exactly the same issue with Maya2018 Update2 (Windows10, x64): I'm unable to import QtUiTools from Qt.
Is it supposed to work/working already for everyone and I'm doing something wrong...?

**Comment by fredrikaverpil** [comment]
`QtUiTools` is not available in `PyQt`, and therefore not supported by Qt.py. Today, Qt.py will only support those bindings which are most usually found across all the different Qt bindings. I believe that Qt.py did not follow this rule when this issue was originally created.

Please have a look at the `QtCompat.loadUi` convenience function here: https://github.com/mottosso/Qt.py#loading-qt-designer-files

You can add custom `QtUiTools` support yourself using `QtSiteConfig.py` if needed, please see https://github.com/mottosso/Qt.py#qtsiteconfigpy
