### ISSUE TITLE
Obsolete QPixmap attributes

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#151]
`QtGui.QPixmap.grabWindow` -> `QtGui.QScreen.grabWindow`
`QtGui.QPixmap.grabWidget` -> `QtWidgets.QWidget.grab`

It seems `grabWindow` can be remapped just fine. But I don't think `grabWidget` can be remapped to `grab` as it takes different arguments.

More info: http://doc.qt.io/qt-5/qpixmap-obsolete.html

On a related note, it doesn't seem like `QtGui.QScreen` has been implemented in PySide2 yet.

**Comment by MHendricks** [comment]
I think QtCompat is going to grow a lot if we add more support for obsolete members, and there are other issues like changed return values that will need to be addressed.

Also, if we keep adding methods to QtCompat its going to be hard to keep track of what objects a function is for. For example `QtCompat.setSectionResizeMode` is for QHeaderView, but you have to read the Qt.py docs or look at the code to figure that out. 

Do we want to define a more strict naming convention? `QtCompat.QHeaderViewSetSectionResizeMode`, or possibly add a namespace object like QtCompat `QtCompat.QHeaderView.setSectionResizeMode`

<br>

I'm working on porting existing PyQt4 code to Qt.py so we can use the code in both Qt4 and Qt5 and have ran into several obsolete method names and different return values. I'm sure I will run into others as I continue as the links below show many obsolete methods.

These fit with the existing QtCompat workaround:
`QtGui.QMouseEvent.angleDelta` -> `QtGui.QMouseEvent.delta`
`QtGui.QHeaderView.setMovable` -> `QtWidgets.QHeaderView.setSectionsMovable`

However, `QtWidgets.QFileDialog`'s `getOpenFileName`, `getOpenFileNames`, and `getSaveFileName` for PyQt4 return `selectedFilename`, while PyQt5, PySide, and PySide2 all return `(selectedFilename, selectedFilter)`. For now, I've made compatibility functions that ensure that PyQt4 returns a empty string for the selected filter and added it to a module I have access to. This probably can go into QtCompat as only PyQt4 needs patched.

Docs:
http://doc.qt.io/qt-5/qwheelevent-obsolete.html#delta
http://doc.qt.io/qt-5/qheaderview-obsolete.html#setMovable

**Comment by mottosso** [comment]
> possibly add a namespace object like `QtCompat.QHeaderView.setSectionResizeMode`

I think that's a good idea. +1

Any thoughts on what it could look like, implementation wise? Maybe put up a PR and we can talk through specifics.

**Comment by MHendricks** [comment]
Qt4:
```cpp
QPixmap QPixmap::grabWidget(QWidget * widget, const QRect & rectangle)
QPixmap QPixmap::grabWidget(QWidget * widget, int x = 0, int y = 0, int width = -1, int height = -1)
```
Qt5:
```cpp
QPixmap QWidget::grab(const QRect &rectangle = QRect( QPoint( 0, 0 ), QSize( -1, -1 ) ))
```

I haven't tested anything yet, but it seems like this could be added to _compatibility_members without the need for a decorator if we accept the caveat that you can't pass the individual values for x, y, width, and height. This seems acceptable because Qt.py is built to match PySide2 not PyQt4.

The interface would be:
```python
from Qt import QtCompat
from Qt.QtWidgets import QWidget
widget = QWidget()
# setup widget
pixmap = QtCompat.QWidget.grab(widget, rect)
```

`QtGui.QScreen.grabWindow` could be handled similarly.

**Comment by MHendricks** [comment]
`Qt.QtCompat.QWidget.grab` has been added to Qt.py in #277 

As discussed in [issue 277](https://github.com/mottosso/Qt.py/pull/277#issuecomment-372912281) we need to make a new pull request to add support for a custom method that will work in all bindings `Qt.QtCompat.grabWindow`. 

There is one caveat though, It looks like `PySide2.QtGui.QPixmap.grabWindow` does not exist in the VFXPLATFORM=2017 tests, so we may not be able to add grabWindow for all builds of PySide2.

**Comment by mangopipeline** [comment]
> `Qt.QtCompat.QWidget.grab` has been added to Qt.py in #277
> 
> As discussed in [issue 277](https://github.com/mottosso/Qt.py/pull/277#issuecomment-372912281) we need to make a new pull request to add support for a custom method that will work in all bindings `Qt.QtCompat.grabWindow`.
> 
> There is one caveat though, It looks like `PySide2.QtGui.QPixmap.grabWindow` does not exist in the VFXPLATFORM=2017 tests, so we may not be able to add grabWindow for all builds of PySide2.

Has this changed as of recently?
i ran into this issue this week, it seem like autodesk products have...

PySide2.QtGui.QScreen.grabWindow (tested max 2019, and maya 2019)

seems that in the spirit of keeping with qt5 convention, the best fix would be not to use the QtCompat name space but instead have "QtGui.QScreen.grabWindow" mapped to QtGui.QPixmap.grabWindow in PySide, and PyQt, no?

**Comment by mottosso** [comment]
Hi @mangopipeline, unsure of what the question is; what is the specific problem you're having at the moment?

**Comment by mangopipeline** [comment]
Well the problem is Qt.py is missing the grabWindow method which you guys are discussing here...

And my question was about the plan to support it via QtCompat name spaces vs just supporting it via the QtGui.QScreen name space

**Comment by fredrikaverpil** [comment]
This seems stale.
