### ISSUE TITLE
Using a pre-existing namespace?

### ISSUE THREAD

**Issue by mccartnm** [mottosso/Qt.py#157]
Qt.py is awesome! I'm slowly transitioning a good chunk of Qt4 stuff and this has been a huge help! Thank you!

I only have one question:
I typically like to mirror my python and c++ code so typing `QtCore.Qt.(something)` isn't my favorite for each time I want to access the `QtCore::Qt` module.
```python
from MyBinding import QtWidgets/QtGui
from MyBinding import QtCore
from MyBinding.QtCore import Qt, SIGNAL
```
is typically how I have my imports go however the last line becomes tricky due to the name of Qt.py

I was just wondering if there was anything you would recommend to avoid the clash (other than say, call each instance of `Qt` in my scripts referring to the `QtCore::Qt` version something like `_Qt`, which isn't out of the question. Just inquiring).

Thanks again!
Cheers.

**Comment by mccartnm** [comment]
As I typed the question out I put together that I could just use an intermediary module to fake it. Which isn't too bad. I'm still up for any other suggestions. That said, anyone is welcome to close this.

```python
# -- /repo/QtBinding.py
import Qt
_Qt = Qt
Qt = _Qt.QtCore.Qt
# ...
# Place any modules into this namespace as 1:1...
# ...

# -- /repo/somefile.py
from QtBinding import Qt # In the clear. Represents the QtCore::Qt and is still only 1 level deep.
```

**Comment by mottosso** [comment]
Hi @mccartnm, thanks for your kind words and feedback!

What are your thoughts on using the `as` mechanism of Python?

```python
# For example..
from Qt.QtCore import Qt as _Qt
# Or..
from Qt.QtCore import Qt as QtCoreQt
```

**Comment by mccartnm** [comment]
Right on I don't mind that solution either. You're method is probably smoother sailing for when trying to import modules I'm not really aware of that other developers might need (i.e.` .ui` loading tools).

Thanks again :)

**Comment by mottosso** [comment]
No problem, thanks for the feedback! Any other questions, just let me know!
