### ISSUE TITLE
setSectionResizeMode

### ISSUE THREAD

**Issue by innerhippy** [mottosso/Qt.py#160]
Hi there,
I'm seeing problems since 0.6.2 (commit 02930e4755de452d871acbd60a10711b583bd4e6).

This commit changed the binding between setResizeMode and setSectionResizeMode (for Qt4) to use a lambda function. The comment in the code mentions "the second argument - hide - does not apply to Qt4", but this method has no parameter called hide, just logicalIndex and mode.

When I call the following:
`QtCompat.setSelectionResizeMode(header, QtWidgets.QHeaderView.ResizToContents)`

I get the following error:
`*** TypeError: setResizeMode expected at least 1 arguments, got 0`

This error was introduced since 0.6.1

Thanks
Will

**Comment by mottosso** [comment]
Thanks for reporting this @innerhippy!

Having a look now.

**Comment by mottosso** [comment]
Let me know how this works out for you, @innerhippy.

**Comment by innerhippy** [comment]
That was also the change I implemented and have tested. Thanks for the quick turnaround!
