### ISSUE TITLE
Issues with querying binding versions

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#164]
I've been on a really old version of Qt.py for a long time and I just noticed that now when I upgraded to Qt.py 0.6.6 that I get this:

```python
>>> from Qt import QtCompat
>>> print(QtCompat.__binding_version__)
0.0.0
>>> print(QtCompat.__qt_version__)
0.0.0
```

When peeking into the code, it seems these attributes are simply never remapped (just their default 0.0.0 values are set).

Before I embark on creating a PR to fix this, was there a specific reason this got changed (or perhaps it was just forgotten when setting up QtCompat)?

**Comment by mottosso** [comment]
You're right, they must never have been implemented in `QtCompat`, let's fix this.
