### ISSUE TITLE
Protection

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt.py#170]
Continuing the discussion from https://github.com/mottosso/Qt.py/issues/152#issuecomment-263722786

### Goal

Enable contributions from individuals who may not be able to guarantee full rights of his work to the recipient.

### Motivation

In Open Source software, many lines of code come from external contributors. The target repository may be licensed under a free-for-all type license, but naturally each line of code written by a contributor defaults to being owned in its entirety by the contributor. It's basic copyright. Sometimes the basic copyright is overridden by a contract the contributor may have signed on accepting a job, in which case everything thing written by the contributor may belong to the company.

What this means for an Open Source repository is that some lines of code are licensed under e.g. MIT whereas other lines of code belong to various individuals and companies.

This wouldn't normally be a problem, if not for the fact that any of these individuals or companies may at any point decide to take action against either the individual who "leaked" proprietary information (or simply, time) or the repository for hosting this information.

### Implementation

We need to find a way of enabling the contributor to provide copyrighted material into the repository, without becoming too much of an obstacle.

**What are our options?**

As far as I can tell, there are three options.

1. Use the Apache license ([reference](https://news.ycombinator.com/item?id=12559169) search for "CLA")
2. Use a Contribution License Agreement ([CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement))
3. Use a Developer Certificate of Origin ([DCO](http://developercertificate.org/))

The Apache license includes a section (5) that implicitly confirms the transaction of IP from contributor to repository, but doesn't protect against if we later decide to change the license from Apache to something else, even MIT, in which case the code is no longer protected by this clause. It would be the simplest solution, as no extra work would be required on anyone's part.

A CLA means signing a document saying you give and are lawfully able to give the intellectual property (i.e. the source code) to the project. See [OpenSubDiv for example](http://graphics.pixar.com/opensubdiv/docs/contributing.html). Then there are automated services (bots), like the [CLAHub](https://www.clahub.com/) and [CLA Assistant](https://cla-assistant.io/) that keep track of who has signed a CLA and comments on a pull-request with a reminder to the contributor that signing is required.

The DCO is similar to a CLA, except you confirm your compliance to [an external document](http://developercertificate.org/) in each pull request.

Docker was using a CLA, [but nowadays](https://blog.docker.com/2014/01/docker-code-contributions-require-developer-certificate-of-origin/) (since 2014) uses a DCO. Here's what their [contributor documentation](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work) has to say about it.

> The sign-off is a simple line at the end of the explanation for the patch. Your signature certifies that you wrote the patch or otherwise have the right to pass it on as an open-source patch. The rules are pretty simple: if you can certify the below (from developercertificate.org)

Here's what that could look like in practice.

- https://github.com/docker/docker/pull/28874

### Discussion

Either of these approaches could work, my main objective is finding one that is least obstructive to making improvements to the project.

Switching to an Apache license have little other effect than introduce this new clause; it is as permissive as MIT if not more so. Introducing a CLA would require us (likely me) to keep track of signed documents, or use an external service to do so. A DCO is less work up-front, but potentially more work long-term; remembering to include that line of confirmation at each pull request, and for us maintainers to point out and remind those that forget.

**Comment by mottosso** [comment]
Can't say for sure, but this suggests to me that one could implicitly accept a CLA simply by linking to and reading it.

- https://cla.github.com/agreement

**Comment by kgambrel** [comment]
A CLA (or DCO, doesn't really matter which) is intended as a protection for what goes into an open source project.   It offers protections to those running open source projects from 3rd parties who might not even be using the project, but claim some kind of infringement.   By having the CLA or DCO you are making sure that each contributor attests that they have the rights to everything they are contributing.   

The CLAs are more attractive to bigger companies than DCOs.  Companies typically don't give developers the rights to sign away ownership of code or other company assets.   This is an issue when the contribution was developed on company time.   

Companies have mixed feelings about CLAs.  One advantage to them is that they put a roadblock in the way of developers just taking action without approval.  On the other hand, CLAs put protections in place for the OSS project and put more responsibility on the company.

I'm looking into the policy of a large company w.r.t. this.  I'll give a more definitive answer for one company when I have it.

**Comment by mottosso** [comment]
Thanks @kgambrel, that's very helpful.

**Comment by fredrikaverpil** [comment]
This one is tricky. 

> Enable contributions from individuals who may not be able to guarantee full rights of his work to the recipient.

@mottosso just curious, is this an existing problem in your company or at some studio you are aware of?

**Comment by mottosso** [comment]
> @mottosso just curious, is this an existing problem at a company you are aware of?

Did you mean to mention @melevine regarding https://github.com/mottosso/Qt.py/issues/152#issuecomment-263722786?

I have personally never experienced or seen this problem; I'd imagine it mostly relates to the really large firms (e.g. ILM) and open source projects (e.g. Docker) where the odds of being sued for copyright infringement is greater, and smaller shops and projects simply follow suit for defensive purposes.

@melevine or @kgambrel might be able to shed some more light on it.

**Comment by fredrikaverpil** [comment]
> Did you mean to mention @melevine regarding #152 (comment)?

Ah, yes. Sorry. Figured I'd ask someone who has experienced this first hand (or so) about what their suggestion/solution was. Has perhaps this already been discussed (can't recall or find anything right now).

**Comment by kgambrel** [comment]
@mottosso , w.r.t. the Github CLA, I'll check with out legal on it.   On first blush, it seems reasonable to me, as it's pretty much in line with the Apache CLA.  It is missing any mention of the possibility that one may be making a contribution from work done during employment by some other entity, but I'm not sure that makes much difference.   Thanks for pointing this out -- I was unaware of a default CLA.

**Comment by mottosso** [comment]
Implemented, all pull-requests must now digitally sign the CLA before being merged. You'll be prompted when you make the pull-request, can't miss it.

**Example**

- https://cla-assistant.io/mottosso/Qt.py?pullRequest=189
