### ISSUE TITLE
# Error: ImportError: file C:\Python27\Lib\site-packages\Qt.py line 419: No Qt binding were found. # 

### ISSUE THREAD

**Issue by tws0002** [mottosso/Qt.py#175]
hi i having this error when using qt in maya 2016 

import Qt
# Error: ImportError: file C:\Python27\Lib\site-packages\Qt.py line 419: No Qt binding were found. # 

but no problem when using qt in maya 2017. 

can anyone help?

Thanks 
Desmond

**Comment by mottosso** [comment]
Hi @tws0002, try not having your system Python on your `PYTHONPATH` when you launch Maya. It may cause Maya to try and run other modules you have there, such as a system-wide PyQt or PySide.

Try putting `Qt.py` in another folder, such as `c:\my_modules` and then adding only that.

**Windows**

```bash
$ copy Qt.py c:\my_modules\Qt.py
$ set PYTHONPATH=c:\my_modules
$ c:\C:\Program Files\Autodesk\Maya2016\bin\maya.exe
```

**Linux**

```bash
$ cp Qt.py ~/my_modules/Qt.py
$ export PYTHONPATH=~/my_modules
$ maya
```

If you are unfamiliar with environment variables, you can also try this from within Maya.

```python
import sys
sys.path.insert(0, r"c:\my_modules")
```

Let me know if you have any problems.

**Comment by tws0002** [comment]
thanks for the quick reply !! 

it work if using ur instruction. 
mean I cannot add  C:\Python27\Lib\site-packages to PYTHONPATH ?

Thanks 
Desmond

**Comment by mottosso** [comment]
> mean I cannot add C:\Python27\Lib\site-packages to PYTHONPATH ?

You can, but it probably isn't a good idea.

If it works when you aren't doing that, then it may be the case that you have another PySide or PyQt installed there that Maya (and Qt.py) is trying to use. But because Maya has a specially compiled version of Python, compiled packages that works for one sometimes might not work with the other.

Best to keep them separate.

**Comment by mottosso** [comment]
If this solves your issue, feel free to close this issue.

**Comment by tws0002** [comment]
Thanks for the help. 

I think because of PySide that I install are in the same folder that have Qt.py!! 
that's the conflict I guess!! after I delete my PySide, problem solve. 

Thanks 
Desmond
