### ISSUE TITLE
__path__ member on Qt module

### ISSUE THREAD

**Issue by osstony** [mottosso/Qt.py#177]
Thank you for creating and continuing to support this project.

I've updated to the 1.0.0.b1 release and ran into a minor issue. I've used the \_\_path__ property on the PySide module in the past and was hoping to continue to do so. The previous version of Qt.py allowed for this by using Qt.\_\_path__. 

I'm hoping this could be made possible again. If setting Qt.\_\_path__ doesn't feel appropriate as it's not truly the path to the Qt.py module then perhaps a member could be added called \_\_binding_path__, which would be set to the bound module's \_\_path__ variable.

*Edited to fix double underscore markdown issue.

**Comment by mottosso** [comment]
Certainly, @osstony. Just to clarify, you are looking for the path to the original binding, and not the path to Qt.py?

I like the `__binding_path__` idea. Feel free to make pull request with this, and increment the version to b2.

**Comment by osstony** [comment]
That is correct, @mottosso.

I'll add it in and get a pull request up soon, thanks!

**Comment by fredrikaverpil** [comment]
Shouldn't `__path__` just work if it exist in all the bindings?

```python
>>> import PySide2
>>> PySide2.__path__
['/usr/local/lib/python2.7/site-packages/PySide2']
```

```python
>>> import PyQt5
>>> PyQt5.__path__
['/usr/local/lib/python3.5/site-packages/PyQt5']
```

```python
>>> import PySide
>>> PySide.__path__
['/usr/local/lib/python2.7/site-packages/PySide']
```

**Comment by osstony** [comment]
Yep, it should work but __path__ is not an available member on the Qt module any longer as of 1.0.0.b1. It was available in previous versions when the Qt module was effectively being set to the binding module.

**Comment by fredrikaverpil** [comment]
Hm. It could also be kind of weird if Qt.__path__ didn't return the path to `Qt.py`.

Technically, Qt.py isn't replacing itself with the desired binding anymore.

Perhaps it would be better to actually put `__path__` on `Qt.QtCompat.__path__`...?

**Comment by osstony** [comment]
Yeah I definitely agree. Adding `__binding_path__` would allow easy access to the path of the binding package and not add unexpected results like `__path__` would.

**Comment by fredrikaverpil** [comment]
> Yeah I definitely agree. Adding __binding_path__ would allow easy access to the path of the binding package and not add unexpected results like __path__ would.

👍

**Comment by mottosso** [comment]
What are your thoughts on this?

```python
import Qt
binding = __import__(Qt.__binding__)
binding.__path__
```

**Comment by osstony** [comment]
Would that be code written by the client to find the binding path? If so I would personally prefer Qt.__binding_path__ rather than going with the additional use of __import__. Just personal preference, I don't have a strong argument for it.

**Comment by mottosso** [comment]
By the client, yes.

The only reason I see **not** going with `__binding_path__` is that it adds another member to Qt.py, and fewer members means less to maintain.

As getting the path from the original binding is a rather obscure edge case (at least to my knowledge) this might be the better way.

Would it be possible for you to give this approach a go, and let me know how it feels after some time has passed? This is something you could do today, without any change to Qt.py

**Comment by osstony** [comment]
Sounds good. I'm only using it in one place and it's simple enough to change.

**Comment by mottosso** [comment]
Cool, thanks.

**Comment by mottosso** [comment]
Feel free to re-open this is more use-cases for it appears.
