### ISSUE TITLE
mixedCase naming convention

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt.py#179]
Currently, `load_ui` is snake_case but Qt and it's bindings are all mixedCase.

I originally chose this convention so as to conform with PEP8 but in retrospect it doesn't seem appropriate as it intermixed two conventions in one library. 

This issue then is about conforming new members of QtCompat to members of other submodules, e.g. QtCore and QtGui.

E.g. `loadUi`

**Comment by fredrikaverpil** [comment]
Hm. I thought it was good not to confuse `load_ui` with e.g. `PyQt4.uic.loadUi` as the behaviour is not 100% identical.

I like the snake case :) primarily because that makes it easy to spot what's part of Qt.py and what's not. But it's not something I would fight over. You decide :)

**Comment by mottosso** [comment]
Good point, good point. It's worth taking into account.

My motivation for wanting mixedCase everywhere is part cleanliness but
mainly discoverability. At this point, *some* members of QtCompat are
mixedCase, such as `setSectionResizeMode` whereas others are snake case.
Which means it isn't enough to remember what a member was called, but also
which case convention it has. It adds unessecary cognitive load.

Let's think about it.

**Comment by fredrikaverpil** [comment]
Yes, I see the dilemma.

I know what the pep says, but let's not get too tangled up in that. The pep is really just guidelines in this case. We're going past that here and need to define our own rules.

Right now I think it would be very weird to rename `setSectionResizeMode` to `set_section_resize_mode`. This wouldn't make any sense.

We could very well conform to mixedCase, such as renaming `load_ui` into `loadUi`. The `translate` function is already named correctly for both snake_case and mixedCase.

But when talking about the functions within `Qt.py`, `tests.py`, `run_tests.py`, I would propose we should keep it snake_case. This all means the following;
* User-facing functions are mixedCase
* Internal Qt.py functions are snake_case

**Comment by fredrikaverpil** [comment]
Also, we could rename `load_ui` into something which cannot easily be confused with `loadUi`(which exists). We could call it e.g. `loadUiFile` (it *does* require a filename at all times).

**Comment by bpabel** [comment]
I'm not sure you need to change the naming, since it's essentially replacing that function and the namespace will be different.

**Comment by mottosso** [comment]
Ok, sounds like we're in agreement on this convention.

```python
from Qt import QtCompat
QtCompat.loadUi(...)
QtCompat.setSectionResizeMode(...)
```

And we'll let the namespace be the differentiator to whether it is an original or wrapped function.

Any additional thoughts, feel free to add.

**Comment by fredrikaverpil** [comment]
I'm guessing we can close this right?

**Comment by mottosso** [comment]
Indeed!
