### ISSUE TITLE
QtCore some methods are not imported into, such as SIGNAL and SLOT, etc

### ISSUE THREAD

**Issue by jeanim** [mottosso/Qt.py#184]
Need to add these methods, such as：
```
    QtCore.Property = _QtCore.Property
    QtCore.Signal = _QtCore.Signal
    QtCore.Slot = _QtCore.Slot
    # add code
    QtCore.SIGNAL = _QtCore.SIGNAL
    QtCore.SLOT = _QtCore.SLOT
```

**Comment by mottosso** [comment]
Hi @jeanim, `SIGNAL` and `SLOT` are deprecated in Qt 5 and will not be included in Qt.py.

See here for the modern workflow.

- http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html

**Comment by jeanim** [comment]
Thank you for your quick reply

I have canceled the SIGNAL method

Greet Job
