### ISSUE TITLE
Override to Disable Setting of API2 for PyQt4

### ISSUE THREAD

**Issue by dgovil** [mottosso/Qt.py#188]
So this is a minor request but currently the `_pyqt4()` function tries to set the sip api to v2 by default.
I was thinking we could add a env var to disable this behavior. By default the env variable would be disabled so that the current behavior is preserved but when it is enabled it would disable the api change.

Something like `QT_USE_API1` which if set to 1, will disable that behavior.

This would let Qt.py be included in bootstrap files without breaking existing code. Otherwise it makes porting legacy code hard.

I can make a pull request if there's no opposition.

Cheers

**Comment by dgovil** [comment]
See pull request: https://github.com/mottosso/Qt.py/pull/189

**Comment by mottosso** [comment]
Thanks @dgovil.

I might not fully understand your use case, but it appears to me that enabling the use of sip v1 would really *hinder* porting of legacy code. Not facilitate it.

For example, the compatibility matrix for sip v1 looks like this.

| Sip  | PyQt4 | PyQt5 | PySide | PySide2
|:-----|:-------:|:------:|:-------:|:---------:
| v1   | X         |           |              |
| v2   | X         | X         | X          | X

Where every binding except PyQt4 uses it by default. Which means that, if you were to enable sip v1 with Qt.py, Qt.py would be usable *only* with PyQt4.

If you could take me through the steps you envision in porting of legacy code with sip v1 enabled, maybe that would provide more some clarity.

**Comment by dgovil** [comment]
Our current situation is that we have lots of code that is not versioned specific to whether it's being consumed by an api1 or api2 environment. Part of this is because they either don't use api1 only features like qvariant or that they cast variables to a Python type for example with `str(Foo)` so would work regardless of API version.

The problem comes if you try and load qt.py in an environment that expects API v1 for even a single script and it suddenly falls apart when it tries to access API v1 features. That makes it hard to let code that uses pyqt4 directly coexist with code that uses qt.py instead till we port everything over at once.

Having an environment variable switch would let us determine when to force the API switch over completely. 

In my experience it's easier to have the API set to v1 and start porting to v2 then the other way around.

Totally agree that it is not something someone should be doing during regular usage, which is why I think the default should be to stay on api2, but I think modifying someone's global environment should also be optional.

**Comment by mottosso** [comment]
Thanks @dgovil, that makes sense.

Onto the [implementation](https://github.com/mottosso/Qt.py/issues/188#issuecomment-290138148).
