### ISSUE TITLE
Dealing with different versions of Qt.py within Maya

### ISSUE THREAD

**Issue by glm-nchaverou** [mottosso/Qt.py#195]
This isn't a bug report, but more of a silly question, sorry:  we've multiple tools developed internally and externally which coexists within the same Maya session. As Qt.py gained a lot of inertia around, some of those tools are using an old version ot Qt.py where some are using a newer version and both are not compatible.
In a lot of tools (internal and external), it's imported the same way which is:
from Qt import blabla
And all those tools are obviously loaded in the PYTHONPATH
Thus, I end up having a couple of conflicts and was wondering what's supposed the best way to deal with this ? Any best practice here ?

**Comment by mottosso** [comment]
Hi @glm-nchaverou, this is an excellent question.

Let's tackle one problem at a time; firstly, the versions should be mostly compatible, with only minor differences amongst 1.0 and pre-1.0. 1.0 currently being in `beta` and unreleased, it's possible there are still differences we need to patch up and there's time for that.

Thus the simplest solution would be to ensure compatibility across versions of Qt.py So let's start there. 

What errors are you getting currently?

**Comment by mottosso** [comment]
Also if you could let me know the versions you are experiencing conflicts with that would help also.

**Comment by glm-nchaverou** [comment]
Fair enough :)

Tool A uses Qt.py 1.0.0.b3 where Tool B uses Qt.py 0.6.1
B imports the following 

> from Qt import load_ui

 but 1.0.0.b3 comes first in PYTHONPATH
Error I get is obviously # ImportError: cannot import name load_ui // as it's now in QCompat

**Comment by glm-nchaverou** [comment]
FWIW I was about to go with relative imports everywhere but both PEP8 and Google Python Style Guide recommend not to use relative imports

**Comment by mottosso** [comment]
> FWIW I was about to go with relative imports everywhere but both PEP328 and Google Python Style Guide recommend not to use relative imports

Could you clarify what you meant here?

By the looks of it, you could solve the problem with an import such as this.

```python
# Tool A with older version of Qt.py
from .Qt import load_ui

# Tool B with 1.0.0b3
from .Qt import QtCompat
QtCompat.loadUi
```

Where `Qt.py` resides in the current package. That way, you specify explicitly which Qt.py to use, regardless of your users PYTHONPATH. The `.` in front assures that only the current package is explored for matching modules.

I [typically](https://github.com/pyblish/pyblish-lite/blob/b1737db3242d485a0377dc52265ebae805268a97/pyblish_lite/app.py#L5) store my Qt.py, alongside other vendor libraries, in a `vendor/` package.

```python
from .vendor.Qt import QtCompat
```

Does this solve your problem?

**Comment by glm-nchaverou** [comment]
> Where Qt.py resides in the current package. That way, you specify explicitly which Qt.py to use, regardless of your users PYTHONPATH. The . in front assures that only the current package is explored for matching modules.

Yep that's what I meant by using relative imports. This totally and this is by far the less intrusive method I found to fix the issue. I wanted to suggest the modification to the owner of the external tools we're having but while searching for good practices, I found the following:

> "Relative imports for intra-package imports are highly discouraged. Always use the absolute package path for all imports. Even now that PEP 328 is fully implemented in Python 2.5, its style of explicit relative imports is actively discouraged; absolute imports are more portable and usually more readable."
https://gist.github.com/pydanny/4735683

But while searching on the PEP8 page, it looks their pov changed:
> Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured. However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose 
https://www.python.org/dev/peps/pep-0008/

And from the Google Python Style Guide
> Do not use relative names in imports. Even if the module is in the same package, use the full package name. This helps prevent unintentionally importing a package twice. 
https://google.github.io/styleguide/pyguide.html

I don't find this latter really relevant so I asked here what will be the best practice :)

**Comment by mottosso** [comment]
I'd take "pydanny"'s position with a grain of salt.

If you ask me, when your code depends on a specific module, make sure it's the module your importing by explicitly stating it.

```python
from . import my_specific_module
```

**Examples:**

- Any module part of your package
- Any vendor packages

If it's more general and you aren't depending on a particular version of it, be implicit.

```python
import my_general_module
```

**Examples:**

- Built-in libraries
- (Compiled) dependencies you can't or won't vendor, e.g. NumPy, PyQt etc.

Personally, I wouldn't take the chance of any internal module being replaced by anything external, unless I had designed specifically for that.

**Comment by mottosso** [comment]
Hey @glm-nchaverou, @fredrikaverpil just made a write-up of how to deal with this issue that I thought would be helpful.

- https://fredrikaverpil.github.io/2017/05/04/vendoring-qt-py/

Welcome to re-open this is the issue persists.

**Comment by glm-nchaverou** [comment]
Thanks !! Really appreciate it :)
