### ISSUE TITLE
QVariant missing

### ISSUE THREAD

**Issue by Fondor1** [mottosso/Qt.py#197]
Trying to utilize QtCore.QVariant yields this error and hangs Python:

`AttributeError: module 'Qt.QtCore' has no attribute 'QVariant'`

Replacing import statement with PyQt5 instead of Qt allows the code to function.

OS: Win7 64bit
Python version: 3.6.1
PyQt5 is installed, not PySide2

**Comment by mottosso** [comment]
Thanks @Fondor1, unfortunately QVariant isn't part of PySide 1 or 2 and will not be included with Qt.py.

See here for details and workaround.

- https://wiki.qt.io/Differences_Between_PySide_and_PyQt#PySide_only_supports_PyQt.27s_.22API_2.22_.28PSEP_101.29
