### ISSUE TITLE
INFO: merging of pyside repositories

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#201]
> Hi all,
>
> you know that the PySide(2) project is sub-divided into three main parts (no tools or examples):
>
> pyside-setup, shiboken and pyside.
>
> We have been fighting with this structure quite often. It is sometimes really hard to keep the repositories in sync when we have several open branches in the workings.
> 
>

> I know there are people who are using shiboken separately. They need to change their workflow a little bit, because they now need to checkout pyside and copy shiboken out of it.
>
> If you see a problem with that, please contact us now. We will for sure find a solution together.

Pleas see more here:
http://lists.qt-project.org/pipermail/pyside/2017-May/002492.html

**Comment by mottosso** [comment]
Looks like Qt.py should remain unaffected, or was there something specific you wanted to point out?

**Comment by fredrikaverpil** [comment]
Oh, yes - Qt.py should not at all be affected. I now realize I should've posted it in #53.

Closing this and making a quick comment about it in there instead...
