### ISSUE TITLE
Upload to Conda

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt.py#202]
### Goal

Expose Qt.py to users of [Conda](https://conda.io)

### Implementation

See here: https://conda.io/docs/build_tutorials/pkgs.html

**Comment by fredrikaverpil** [comment]
This can currently be achieved like this:

```bash
# Example: Windows
avctivate myEnv
pip install Qt.py
deactivate

# Example: Unix
source activate myEnv
pip install Qt.py
deactivate

# Example: just pip (Windows)
~/path/to/myEnv/Scripts/pip install Qt.py

# Example: just pip (Unix)
~/path/to/myEnv/bin/pip install Qt.py
```

**Comment by mottosso** [comment]
I think what folks are looking for is..

```bash
$ conda install Qt.py
```

**Comment by tokejepsen** [comment]
> I think what folks are looking for is..

Have you had requests about this?
Pip installing with conda is quite common.

**Comment by mottosso** [comment]
I've seen Qt.py being compared to qtpy and this was one of the cons of Qt.py, so I figured why not. Hopefully I can set it up such that it deploys automatically alongside deployment to PyPI, then it'd be a one-off problem solved.

**Comment by fredrikaverpil** [comment]
I also think "why not", if there's time.

We're using miniconda to set up all python environments here in our studio and we pip install Qt.py just fine. Not sure if I would conda install it, even if it was possible. But it doesn't hurt to set up an automated deploy if possible.

**Comment by fredrikaverpil** [comment]
The real benefit of conda/conda-forge is setting up the base environment and installing certain packages and not having to deal with compilation woes. So offering Qt.py on conda-forge would just be a convenience.

**Comment by fredrikaverpil** [comment]
In progress...

https://github.com/conda-forge/staged-recipes/pull/3832

**Comment by fredrikaverpil** [comment]
@mottosso I took the liberty to add you as a maintainer of the conda package.

**Comment by fredrikaverpil** [comment]
I received a [request from conda-forge](https://github.com/conda-forge/staged-recipes/pull/3832#pullrequestreview-59126916) that we include the `LICENSE` file in the [Qt.py tarball](https://pypi.org/project/Qt.py/#files).

![screen shot 2017-08-29 at 06 15 47](https://user-images.githubusercontent.com/994357/29804243-a68172a0-8c81-11e7-9b7c-a4ca80d0d69e.png)

**Comment by fredrikaverpil** [comment]
Closing this, as Qt.py was uploaded already. Tracking some further changes in https://github.com/mottosso/Qt.py/pull/242
