### ISSUE TITLE
SIGNAL in Qt.py

### ISSUE THREAD

**Issue by sainthk** [mottosso/Qt.py#204]
I tried to make a connection with SIGNAL,
(converting PyQt4 codes to Qt.py)
but got the next error;

**from Qt import QtCore, QtGui, QtWidgets
...
self.connect(self.expandAllAction, QtCore.SIGNAL("triggered(bool)"), self.expandAllCB)**

Error:
**'module' object has no attribute 'SIGNAL' #**

Do I have to use the new syntax way to make a connection?
https://wiki.qt.io/Signals_and_Slots_in_PySide

**Comment by mottosso** [comment]
Hi @sainthk, yes you are right, you'll have to use the new syntax as Qt.py only exposes the Qt 5 API and SIGNAL has been deprecated.

Similar question https://github.com/mottosso/Qt.py/issues/184
