### ISSUE TITLE
Missing attributes

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#21]
These attributes currently do not exist on the `Qt` object, which are mentioned in the [README](https://github.com/mottosso/Qt/blob/master/README.md#documentation):

	# Reference to version of Qt, such as Qt 5.6.1
	print Qt.__qtVersion__
	# Reference to version of binding, such as PySide 1.2.6
	print Qt.__bindingVersion__
	# Version of this project
	print Qt.__version__

**Comment by mottosso** [comment]
PR is welcome!

**Comment by fredrikaverpil** [comment]
@mottosso definitively :) Tied up atm but figured I'd just post that as a reminder.
