### ISSUE TITLE
Binding specific replacement mappings as a dictionary, similar to _common_members

### ISSUE THREAD

**Issue by Ahuge** [mottosso/Qt.py#211]
This is a feature request.

I would love if all of the per binding tomfoolery that is done in the "_pyside", "_pyqt4", etc functions was global as a constant mapping dictionary. 
This would allow other packages relying on Qt.py to know the extent of changes being made.

I have a PR incoming for this.

**Comment by mottosso** [comment]
> tomfoolery

Hah! I learnt a new expression today. :)

Thanks @Ahuge, as discussed this would be a fantastic enhancement to the Qt.py project.

**Comment by Ahuge** [comment]
I have a part two with this that I would like to implement.

Adding support for reassignments to custom functions, for example:

{
    "pyqt4": {
        "uic.loadUi": "QtCompat.loadUi"
    }
}

The problem being that QtCompat.loadUi maps to the custom _loadUi function.


I will create a branch and PR tonight but my thought is that we could support the following "mapping"

{
    "pyqt4": {
        "uic.loadUi": ["QtCompat.loadUi", _loadUi]
    }
}

Where if the value is a list|tuple, we are saying that we are actually replacing the functionality of <key> with <value[1]> and you call it with <value[0]>

So it's more of a replacement than a moved mapping.


I'd love to hear your thoughts on this

**Comment by mottosso** [comment]
There's a similar request [here](https://github.com/mottosso/Qt.py/pull/210), with a similar method of achieving results.

My thoughts in that thread is that the added benefits might not be worth the added complexity. I think what make it more easy to judge is if we could turn things around, and work top-to-bottom - looking first at the feature you are looking to support with these smaller enhancements. That way we'd have some way of justifying the necessary complexity.

What do you think about making a PR with (failing) tests representing the final product you are looking to implement?

**Comment by Ahuge** [comment]
This was solved in #285
