### ISSUE TITLE
AttributeError: module 'QtCompat' has no attribute 'loadUi'

### ISSUE THREAD

**Issue by iwootten** [mottosso/Qt.py#213]
Under fresh install of Python 3.6 and using PyQt 5.8.2/sip 4.19.2 on MacOS 10.12, along with a fresh checkout of master, I hit the following issue when a call to Qt.py is made:

```
File "nodz_demo.py", line 1, in <module>
   from Qt import QtCore, QtWidgets
File "/Users/ian/dev/iwootten/python/nodz/vendor/Qt.py", line 1109, in <module>
    _install()
File "/Users/ian/dev/iwootten/python/nodz/vendor/Qt.py", line 1106, in _install
    Qt.QtCompat.load_ui = Qt.QtCompat.loadUi
AttributeError: module 'QtCompat' has no attribute 'loadUi'
```

I'm in a clean virtualenv with pyqt/sip symlinked to site-packages, and Qt.py seems to work fine when L1106 is commented out.

**Comment by mottosso** [comment]
Thanks @iwootten.

Does it work outside of virtualenv? Can you `from PyQt5 import QtWidgets` from within your virtualenv?

**Comment by iwootten** [comment]
Yes, PyQt5 works fine in/outside the virtualenv - probably should have mentioned that.

**Comment by mottosso** [comment]
Ok, I think I see what's going on here.

Could you test to see if this works?

```python
from PyQt5 import uic
```

**Comment by iwootten** [comment]
That fails with an ImportError.

**Comment by mottosso** [comment]
Ok, then it looks like the distribution you've got doesn't include `loadUi`. Unexpected, but it shouldn't cause trouble for Qt.py, so this is a bug. I'll have a look at this.

**Comment by iwootten** [comment]
Cheers!

**Comment by fredrikaverpil** [comment]
You need Qt Creator in order for PySide2 to detect QtUiTools and build that. Could that be the reason why?
