### ISSUE TITLE
QtCompat.loadUi layout check Passes PyQt4, fails PySide

### ISSUE THREAD

**Issue by tbttfox** [mottosso/Qt.py#215]
The default empty layout object `bool(QMainWindow().layout())` evaluates to `True` in PySide and `False` in PyQt4.

So the check in `_loadUi` :
`    if hasattr(baseinstance, "layout") and baseinstance.layout():`
produces different results based on the backend.  This means we can't ever load a .ui file onto a QMainWindow baseinstance in PySide. 

I think the way to handle this is to also check if the layout object `.isEmpty()`

**Comment by mottosso** [comment]
Thanks for reporting this @tbttfox.

I'd love to put in a test for this, but I'm unfamiliar with how to actually use this function. Your suggestion for `.isEmpty()` sounds reasonable. Do you have something in mind I can use to capture this bug, and see it vanish by implementing the workaround? If you could share with me an example of the problem in action, that would be fantastic and we could plug this hole quickly.

Alternatively, you are most welcome to provide a pull-request with a suggested solution and/or test.

**Comment by tbttfox** [comment]
OK, Made a PR #217
