### ISSUE TITLE
'module' object has no attribute 'loadUi'

### ISSUE THREAD

**Issue by simonreeves** [mottosso/Qt.py#218]
Hello,
I am just beginning to implement `Qt.py` so I am trying to get a clean environment to deal with this error.

I do not get this error when I  `import Qt` inside Houdini - but when trying to just run it in windows command line.

``` File "\\my\server\Lib\Qt.py", line 1240, in _install
    Qt.QtCompat.load_ui = Qt.QtCompat.loadUi
AttributeError: 'module' object has no attribute 'loadUi'
```
 `PySide` & `PySide2` are both able to be imported and I was unsure if I also need PyQt? Or.... I'm not sure. 

This is windows7/Python27

Thanks!

**Comment by fredrikaverpil** [comment]
What version of Qt.py are you on and which binding are you using?

This is on macOS:

```bash
# Install environment
conda create --mkdir -p ~/code/qtpytest python=2.7 pyqt
~/code/qtpytest/bin/pip install -U Qt.py
```

```bash
# Run test
~/code/qtpytest/bin/python
Python 2.7.13 | packaged by conda-forge | (default, May  2 2017, 13:29:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Qt
>>> print(Qt.__version__)
1.0.0
>>> Qt.QtCompat.load_ui = Qt.QtCompat.loadUi
>>> 
```

I don't see any errors.

**Comment by simonreeves** [comment]
Thanks for your reply!

Here is  the version from the file as I can't import Qt
`__version__ = "1.1.0.b1"`
I was just wondering if that specific error would show a clear issue, or if my set up is wrong - (I should clean my environment).

If I have PySide2 available to import and Qt it should just work is that all that is required?

**Comment by fredrikaverpil** [comment]
> Here is the version from the file as I can't import Qt

What do you mean, you can't import Qt?

> If I have PySide2 available to import and Qt it should just work is that all that is required?

Yes.

**Comment by simonreeves** [comment]
> What do you mean, you can't import Qt?
That is my issue in my original post.
In windows command line, I run python, then `import Qt` and get the error

**Comment by fredrikaverpil** [comment]
Could it be possible that there's a missing module in Houdini?  
In this case `PySide2.QtUiTools.QUiLoader`?

Try this:

```
from import PySide2
from PySide2 import QtUiTools
print(QtUiTools.QUiLoader)
```

Does that work?

**Comment by simonreeves** [comment]
Ah thank you, that is the issue.
```
>>> from PySide2 import QtUiTools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
```
I removed `PySide2` and left `PySide` only and it worked fine so that makes sense to me.

I think I need to source a more appropriate PySide2 module! I can't use pip because it is python 3? I need to understand that part better.

**Comment by fredrikaverpil** [comment]
@simonreeves did you build PySide2 yourself and somehow left out that module?

If you follow that blog post you need to make sure to check out the `5.6` branch of `pyside-setup`. I still haven't gotten around to adding that piece of info to that blog post yet. I better do it now I guess... ;)

Perhaps these will be of help too: https://bintray.com/fredrikaverpil/pyside2-wheels/development#files/use-qt-5.6%2Fwindows6.3.9600

**Comment by simonreeves** [comment]
I didn't build it myself I think it came from a DCC. The module `QtUiTools.pyd` does exist but it requires the dll too?
Thanks I'll look into (learn) those links also...

**Comment by simonreeves** [comment]
I'm starting to getting the impression I should just switch to python3 for standalone

**Comment by fredrikaverpil** [comment]
> I'm starting to getting the impression I should just switch to python3 for standalone

I'd definitively recommend that, especially on Windows, yes.

I'll close this issue and we can re-open it if the issue persists.

**Comment by simonreeves** [comment]
I've just always assumed that using 3 while the DCCs are 2 is a bad idea... But as long as I keep my scripts compatible it shouldn't be an issue... 

Thanks for your help! & Qtpy

**Comment by mottosso** [comment]
> I've just always assumed that using 3 while the DCCs are 2 is a bad idea... 

If it helps, all code I've written for the past few years have been compatible with both Python 2 and 3, preparing for that inevitable switch into Python 3 land.

**Comment by fredrikaverpil** [comment]
Yeah, I second what @mottosso said. A tip is to use a Python 3 linter (I use pylint). That way you'll quickly see what errors you are doing when you are used to writing Python 2-code.

**Comment by simonreeves** [comment]
> for that inevitable switch into Python 3 land

yes exactly if its on the cards for 2019!

>use a Python 3 linter

good plan!
