### ISSUE TITLE
Qt.py does not find PySide2

### ISSUE THREAD

**Issue by alby128** [mottosso/Qt.py#222]
Somehow it seems that I managed to install PySide2 on my system (using https://github.com/fredrikaverpil/pyside2-wheels). So now, for example, in a python2 console I can execute "from PySide2 import QtGui" without errors. But if I try to do "from Qt import QtGui" I get

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/Qt.py", line 1109, in <module>
    _install()
  File "/usr/local/lib/python2.7/site-packages/Qt.py", line 1106, in _install
    Qt.QtCompat.load_ui = Qt.QtCompat.loadUi
AttributeError: 'module' object has no attribute 'loadUi' 

I ported a PySide program to Qt and now I was trying to replace PySide with PySide2, but this issue prevented me to use the Qt shim with PySide2. Thanks.

**Comment by mottosso** [comment]
Related https://github.com/mottosso/Qt.py/issues/213

**Comment by mottosso** [comment]
This should have been fixed, try this to upgrade your install to the current pre-release.

```bash
$ pip install --pre -U Qt.py
```

**Comment by alby128** [comment]
This fix works, thanks!
