### ISSUE TITLE
qt.py in KATANA

### ISSUE THREAD

**Issue by wblion** [mottosso/Qt.py#228]
File "D:\git_work\YQ_work\yq_worknew\yq_work\lib\Qt\Qt.py", line 1013, in <module>
    _install()
  File "D:\git_work\YQ_work\yq_worknew\yq_work\lib\Qt\Qt.py", line 981, in _install
    raise ImportError("No Qt binding were found.")
ImportError: No Qt binding were found.

can you help me

**Comment by fredrikaverpil** [comment]
Hello,

I presume you can import a Qt binding directly?
Such as `import PySide` or `import PySide2`. Right?

**Comment by wblion** [comment]
i can import PyQt4

**Comment by fredrikaverpil** [comment]
Hm, okay. Did you set `QT_PREFERRED_BINDING` to something other than `PyQt4`?

**Comment by mottosso** [comment]
Could you also tell us which version of Qt.py you are using? In the Qt.py file, there is a variable `__version__`. And also what platform and version of Katana you are using.

Also try setting the `QT_DEBUG` environment variable before importing Qt.oy.

**Comment by mottosso** [comment]
Sorry I meant `QT_VERBOSE`

**Comment by wblion** [comment]
qt.py version is __version__ = "1.0.0.b3"    katana version  Katana2.5v1 win

**Comment by mottosso** [comment]
Perfect, and could you tell me what the output is when setting `QT_VERBOSE=True`?

For example..

```python
import os
os.environ["QT_VERBOSE"] = "True"
import Qt
```

You should be seeing some messages being printed when you try and `import Qt`.

**Comment by wblion** [comment]
import os
os.environ["QT_VERBOSE"] = "True"
import Qt

this is out put
File "<string>", line 4, in <module>
    import Qt
  File "D:\git_work\YQ_work\yq_worknew\yq_work\lib\Qt\Qt.py", line 1013, in <module>
    _install()
  File "D:\git_work\YQ_work\yq_worknew\yq_work\lib\Qt\Qt.py", line 981, in _install
    raise ImportError("No Qt binding were found.")
ImportError: No Qt binding were found.

**Comment by mottosso** [comment]
Thanks @wblion.

I'm having trouble identifying where the error is coming from, as line 981 with your version is [here](https://github.com/mottosso/Qt.py/blob/533ea03d931e5525040ec1ff80e7dbb1918f85a5/Qt.py#L981) and looks like this.

```python
    if hasattr(Qt, "_QtUiTools"):
        Qt.QtCompat.loadUi = _loadUi
```

I think you may have either have a modified version of Qt.py, or the version is incorrect. Would it be possible for you to paste the contents of the `Qt.py` file on https://gist.github.com? Then I could see where the error is coming from and hopefully narrow this down.

**Comment by mottosso** [comment]
Sorry, I misread the version as `1.1.0.b3` when it was `1.0.0.b3`. Line 981 for that version is [here](https://github.com/mottosso/Qt.py/blob/1.0.0.b3/Qt.py#L981) and looks like this.

```python
        for member in members:
            # Accept that a submodule may miss certain members.
            try:
                their_member = getattr(their_submodule, member)
            except AttributeError:
                _log("'%s.%s' was missing." % (name, member))
                continue
```

It still looks a little off, and I can't quite place why it would throw such an error. It would be best if you could either paste the entirety of your file as a gist, or try and use a later version from [one of the releases](https://github.com/mottosso/Qt.py/releases) or via `pip install`.

**Comment by wblion** [comment]
very thanks 
now  i clone new version of qt.py __version__ = "1.1.0.b3"

it same problem 

File "<string>", line 3, in <module>
    import Qt
  File "D:\git_work\YQ_work\yq_worknew\yq_work\lib\Qt\Qt.py", line 1422, in <module>
    _install()
  File "D:\git_work\YQ_work\yq_worknew\yq_work\lib\Qt\Qt.py", line 1389, in _install
    raise ImportError("No Qt binding were found.")
ImportError: No Qt binding were found.

**Comment by fredrikaverpil** [comment]
@wblion I'm not familiar with Katana, but is it possible that parts of the error ends up in some kind of script editor and parts of the error ends up in a commandline window?

**Comment by wblion** [comment]
i just run in katana Python tab
import pyqt4   is ok

 
it is full mess
>>> import os
>>> os.environ["QT_VERBOSE"] = "True"
>>> import Qt
Order: 'PySide2', 'PyQt5', 'PySide', 'PyQt4'
Trying PySide2
ImportError: No module named PySide2
Trying PyQt5
ImportError: No module named PyQt5
Trying PySide

ImportError: No module named PySide
Trying PyQt4
ImportError: API version already set to 1
File "<string>", line 4, in <module>
    import Qt
  File "D:\git_work\YQ_work\yq_worknew\yq_work\lib\Qt\Qt.py", line 1013, in <module>
    _install()
  File "D:\git_work\YQ_work\yq_worknew\yq_work\lib\Qt\Qt.py", line 981, in _install
    raise ImportError("No Qt binding were found.")
ImportError: No Qt binding were found.

**Comment by mottosso** [comment]
> ImportError: API version already set to 1

There we go. This is the problem. @fredrikaverpil could you take over? :)

**Comment by wblion** [comment]
@fredrikaverpil @mottosso very thanks for you help me.

**Comment by fredrikaverpil** [comment]
@wblion I see what's going on now.

Qt.py always assumes you want SIP API v2 so it attempts to set this: https://github.com/mottosso/Qt.py#sip-api-v2

Before you import Qt.py, there are a number of environment variables you can register to change the behavior of Qt.py. One such variable is `QT_SIP_API_HINT`: https://github.com/mottosso/Qt.py#environment-variables

Try to set `QT_SIP_API_HINT=1` prior to importing your build of PyQt4.

**Comment by mottosso** [comment]
We should update that error message to be more explicit about that.

- https://github.com/mottosso/Qt.py/issues/230

**Comment by mottosso** [comment]
And @wblion, this should be better documented on our part, but using the latest commit of Qt.py is not recommended for production, as there will be no way for you to include a version number with your bug report.

It would be much preferable if you either install via pip or pick a GitHub release from [here](https://github.com/mottosso/Qt.py/releases).

**Comment by wblion** [comment]
@mottosso @fredrikaverpil  it is works ,very tank so coll, ok  I'll do what you tell me。vrey thanks.
