### ISSUE TITLE
Missing QItemSelectionRange

### ISSUE THREAD

**Issue by sporty** [mottosso/Qt.py#232]
Thank you for maintenance Qt.py.

I did not see it for a while since merged my pull requests, but I confirmed that the processing of QItemSelectionRange has disappeared at the next revision.

Could you check it out?

https://github.com/mottosso/Qt.py/commit/1bd56298a5a8c45ff84d09189f0236fd99a991f2

**Comment by sporty** [comment]
Sorry, "next revision" may not have been accurate.

It exists in 1.0, it does not exist in 1.1.0b1.

**Comment by mottosso** [comment]
Thanks for reporting this @sporty.

A PR is most welcome, otherwise I'll take a look as soon as I am able.

**Comment by RafeSacks** [comment]
Hi, just for clarity for anyone else searching this topic: `QItemSelectionRange` moved from `QtGui` to `QtCore`

**Comment by Ahuge** [comment]
Looks like membership.py is picking it up correctly, 

So perhaps we just need a new release built with that membership?

@mottosso, @fredrikaverpil   what is the status of that new membership that got merged in. Is it stable enough for a release?

**Comment by mottosso** [comment]
Yeah, looks like it's been missed out. Happy to see a PR for it.

**Comment by RafeSacks** [comment]
@mottosso : Is a PR needed? It sounds like it is there but needs a build? (See @Ahuge question at the end of his reply.)

**Comment by Ahuge** [comment]
Yeah I was looking at the membership code and running it locally, it appears to pick up the QItemSelectionRange + a few other missing ones.

I don't have access to a machine with docker on it so I don't have the ability to build the new membership for all bindings but I think it would work if we made a new release after running the membership test.

**Comment by mottosso** [comment]
There isn't anything being built. That module is only used for tests. We need a PR wit that member added to the list of members in the Qt.py module.

**Comment by Ahuge** [comment]
Ah ok, I assumed that the build_membership  helped build the Qt.py module programatically.

**Comment by Ahuge** [comment]
I understand what is needed now

**Comment by Ahuge** [comment]
r1.1.0.b6 solves this.

I think this can be closed. 
@sporty do you agree?


Thanks all!

**Comment by RafeSacks** [comment]
Tested on our end and this seems resolved to me too. Thanks!!

**Comment by sporty** [comment]
I agree!
Thanks!
