### ISSUE TITLE
Wrapper for compiling ui files

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#24]
Do we also wish to provide a facility to support differences between PySide/PyQt?

```python
from Qt import QtCore
from Qt import QtWidgets
from Qt import __binding__
if __binding__.startswith('PySide'):
    from Qt import QtUiTools
    import pysideuic
elif __binding__.startswith('PyQt'):
    from Qt import uic
    import sip
```

I'm using the above frequently now, but it could have looked like this with the help of the `Qt` module:

```python
from Qt import QtCore
from Qt import QtWidgets
from Qt import uic
from Qt import generator
```

In this case, perhaps `uic` and `generator` should be prefixed to stress they are custom wrappers.

**Comment by mottosso** [comment]
Ah, interesting, I've never used these myself. What do they do?

**Comment by fredrikaverpil** [comment]
They are used to load .ui files.

These are the most common modules to use when loading a .ui file:
- PyQt4.uic
- PySide.QtUiTools.QUiLoader

However, there's an issue with PySide's QUiLoader which makes it behave differently than PyQt's uic. When you've loaded the UI using QUiLoader, you don't access the objects through the expected namespace (if you consider PyQt to be "god"). I believe that could have been why `pysideuic` was developed, as it fixes that – but I don't for a fact this was the reasoning on why pysideuic was made.

Here's an example: https://gist.github.com/fredrikaverpil/a70f38c8b04c49aaf73c1d22846f924a

So far, I can tell that this same behaviour is true for PyQt5/PySide2.

It's important to note that functions of PyQt4.uic and pysideuic are not the same.

I'm not sure myself if this is a good idea, and I might have a better idea at the end of the week.

**Comment by mottosso** [comment]
> Here's an example

Isn't there an easier way of doing that? It seems awefully complex.

With PyQt4 there is this.

- http://pyqt.sourceforge.net/Docs/PyQt4/designer.html#PyQt4.uic.loadUi

If we're wrapping any of that, I would expect something along these lines.

```python
from Qt import loadUi
```

Where `loadUi` is our own version and behaves like PySide2.

**Comment by fredrikaverpil** [comment]
> It seems awefully complex.

Agreed. But there's no real equivalent of `PyQt4.uic.loadUi` in PySide. Instead, you have to use  `PySide.QtUiTools.QUiLoader`. Which is why I've gone through all that trouble.

`PySide.QtUiTools.QUiLoader` works fairly well if you only load one ui file, [example here](http://www.chrisevans3d.com/pub_blog/pyqt4-uic-module-example/) with comparisons to `PyQt4.uic.loadUi`.

**Comment by mottosso** [comment]
> Agreed. But there's no real equivalent of PyQt4.uic.loadUi in PySide.

Ah, I see.

I'd be fine with a `loadUi` convenience function coming from this project, that does what it does for PyQt. That seems like the simplest method.

> I'd like to close my own question with a "no, not right now anyways".

Let's keep it open, the question is bound to come up again sooner or later.

**Comment by fredrikaverpil** [comment]
So perhaps it could be interesting to explore after all. I've been tinkering and [here's a gist](https://gist.github.com/fredrikaverpil/2bcd40900a44ae0a89dbc60980804fdf).

Some issues:

- UI file is not loaded into `self`. Instead it is loaded into e.g. `self.ui`.
- The second UI file cannot be loaded into `self.ui` and any widgets we need to access needs to be moved into `self.ui` manually.
- Haven't tested this with PyQt5 as that errors out at the moment https://github.com/mottosso/Qt.py/issues/28

**Comment by mottosso** [comment]
I'll let you decide what's best here, as I don't use this feature.

**Comment by fredrikaverpil** [comment]
Sure, will do. I'll be back with a suggestion.
