### ISSUE TITLE
Beta release published to PyPi?

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#243]
@mottosso What just happened? I could swear it just said 1.0.0 at PyPi.

![screen shot 2017-08-29 at 16 19 23](https://user-images.githubusercontent.com/994357/29825824-d504beee-8cd5-11e7-94cb-16921b868151.png)

**Comment by mottosso** [comment]
Yeah, they're published, but with the `b` at the end they won't install until you explicitly want to.

```bash
$ pip install Qt.py
$ python -c "import Qt;print(Qt.__version__)"
1.0.0
$ pip install Qt.py --pre -U
$ python -c "import Qt;print(Qt.__version__)"
1.1.0b3
```

**Comment by fredrikaverpil** [comment]
Oh. Phew! :)
