### ISSUE TITLE
setupUi inclusion

### ISSUE THREAD

**Issue by dgovil** [mottosso/Qt.py#244]
I just wanted to create an issue to discuss this.

PyQt4/5 has a member called setupUi that connects the signals automatically to the slots based on their naming.
Personally I never use this but I am getting a lot of requests to add this to our facility copy of `Qt.py`.

Before I do that, I wanted to check if this was something anyone else has already ported and would be willing to share? 
Also I want to check if this is something that you guys think should be included in `QtCompat` by default, in which case I can write it and make a pull request.

Cheers

**Comment by fredrikaverpil** [comment]
I never used it either. But I would say that a PR is always welcome :)

It would be easier to discuss the usefulness, implementation and maintainability once there is a PR, at least for me personally as I don't have much experience with setupUi

**Comment by fredrikaverpil** [comment]
I would like to add (and stress) that were like to keep the complexity of Qt.py down and avoid having to maintain new code built on top of bindings, which users start to rely on. So please remap and utilize as much existing binding functionality as possible.

**Comment by dgovil** [comment]
> I would like to add (and stress) that were like to keep the complexity of Qt.py down and avoid having to maintain new code built on top of bindings

+1

Having to maintain `Qt.py` internally, I definitely appreciate its current level of complexity (or lack thereof). 
I'll try and make use of as much existing functionality as possible.

Hopefully can have a pull request for next week.

**Comment by dgovil** [comment]
Sorry forgot to update this ticket, (I thought I had)
The setupUI is just an auto method that gets generated when running the uic conversion. No need for Qt.py to support it
