### ISSUE TITLE
QLayout.setMargin

### ISSUE THREAD

**Issue by Ahuge** [mottosso/Qt.py#246]
Hey, so QLayout.setMargin is technically deprecated.

PySide2 has included it, PyQt4 includes it, but PySide does not.

So if you load Qt.py and it picks the PySide binding the following code throws an exception:
```python
from Qt import QtWidgets
layout_ = QtWidgets.QHBoxLayout()
layout_.setMargin(4)
```

But on every other binding it will do the PySide equivalent of the following:
```python
from Qt import QtWidgets
layout_ = QtWidgets.QHBoxLayout()
layout_.setContentsMargins(4, 4, 4, 4)
```

Should Qt.py support PySide's lack of setMargin?

**Comment by mottosso** [comment]
Good question.

I'd imagine PySide2 includes it because of its history from PySide(1). Once they come to their senses, I expect it to be excluded.

I'd vote no, let's not support it. That said, we can't prevent users from accessing it where it's available, which is a little unfortunate..

**Comment by mottosso** [comment]
This makes for a good subject to appear when users search for these keywords.
