### ISSUE TITLE
Issues with Deadline10

### ISSUE THREAD

**Issue by simonreeves** [mottosso/Qt.py#248]
I have been upgrading from Deadline 7 to 10. From what I have worked out so far 10 is using PyQt5 (it is included in its `Lib\site-packages`)

My first error (from loading my own modules that import Qt)
```
AttributeError : 'module' object has no attribute 'PYQT_VERSION_STR' (Deadline.Events.DeadlineEventPluginException)
```

Which led me to this issue https://github.com/mottosso/Qt.py/issues/40 
So I tried:
```
import PyQt5
print(PyQt5.__version__)
```
which returned this error in deadline
```
AttributeError : 'module' object has no attribute '__version__' (Deadline.Events.DeadlineEventPluginException)
```

So I think that is the issue? I'm not sure how to avoid it exactly...

I tried this debug of Qt which fails after trying to load PyQt5 again

```
2017-09-15 15:06:01:  EventOrder: 'PySide2', 'PyQt5', 'PySide', 'PyQt4'
2017-09-15 15:06:01: Trying PySide2
2017-09-15 15:06:01: ImportError: No module named PySide2
2017-09-15 15:06:01: Trying PyQt5
2017-09-15 15:06:01:  Events plugin 'AnalogEvent' could not be loaded from the repository because: An error occurred in function "GetDeadlineEventListener" the event plugin script file "AnalogEvent.py": AttributeError : 'module' object has no attribute 'PYQT_VERSION_STR' (Deadline.Events.DeadlineEventPluginException)
```

**Comment by mottosso** [comment]
That is mighty strange. It looks like `PYQT_VERSION_STR` is missing from their distribution of PyQt5.

As this variable isn't critical to the function of Qt.py, I'd accept a pull-request making it optional (replacing it with e.g. `"unknown"`).

**Comment by simonreeves** [comment]
I did that but then had more missing. I dont need to load the ui at all at this point so I am going to rework my modules instead I think. I may mention this to thinkbox anyway to see what they say.

Thanks for your help!

**Comment by RandomInsano** [comment]
Hey guys! Answering here since the ticket'd be locked away forever.

We're building PyQt with the standard SIP tooling as far as I know. I did a bit of digging, and it looks like the PYQT_VERSION_STR lives in QtCore:

```python
import PyQt5

print(dir(PyQt5.QtCore))
```
That outputs this inside Deadline's Python.net instance:
['PYQT_CONFIGURATION', 'PYQT_VERSION', 'PYQT_VERSION_STR', 'QAbstractAnimation', 

Mostly a Thinkbox thing, but to get access to Qt from within Deadline you run your script like so:
C:\Users\username\Downloads>"c:\Program Files\Thinkbox\Deadline10\bin\deadlinecommand.exe" executescript c:\Users\username\Downloads\TestPyQt.py

**Comment by fredrikaverpil** [comment]
> That is mighty strange. 

Indeed. I've never had issues with this and I've been using the conda version of PyQt5 together with Qt.py without ever seeing this:

```
conda install pyqt==5.6 qtpy
```

> looks like the PYQT_VERSION_STR lives in QtCore:

Is it possible that this is a more recent change?
Is Deadline built against Qt 5.6?

**Comment by fredrikaverpil** [comment]
Hm! Here's an investigation I made a while back, where you can see it was indeed accessible directly under PyQt5.QtCore: https://github.com/mottosso/Qt.py/issues/40

**Comment by simonreeves** [comment]
> @simonreeves can you check and see if you can access PyQt5.QtCore.PYQT_VERSION_STR?

Yes it worked. I ran a script like @RandomInsano suggested and it returns the version
```
import PyQt5
print(PyQt5.QtCore.PYQT_VERSION_STR)
```
> which is also exactly where Qt.py looks for it today

Well now a couple days later it seems to be working fine. So I have no idea what was happening before...

**Comment by mottosso** [comment]
Time heals all bugs!
