### ISSUE TITLE
Houdini 16 : hython + PySide2

### ISSUE THREAD

**Issue by nyue** [mottosso/Qt.py#249]
Hi,

  [Note: I have tested the python code and *.ui with various versions of Maya, they work fine]

  Just documenting my observations.

  I am using the following example as a starting point to learn how to use Qt.py with Houdini 16

  https://github.com/mottosso/Qt.py/blob/master/examples/loadUi/baseinstance1.py

  On OS X, I get these errors

>$hython QtStatusDialogHostApp.py 
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

>Reinstalling the application may fix this problem.
Abort trap: 6

  On CentOS, I get similar errors but the plugin required is "xcb"

[QtStatusDialogHostApp.py.txt](https://github.com/mottosso/Qt.py/files/1309259/QtStatusDialogHostApp.py.txt)

Cheers

**Comment by mottosso** [comment]
Thanks @nyue. Can you confirm that you are able to run code containing any widget in this way?

For example..

**any_widget.py**

```python
import sys
from Qt import QtWidgets
app = QtWidgets.QApplication(sys.argv)
button = QtWidgets.QPushButton("Hello")
button.setFixedSize(400, 400)
button.show()
app.exec_()
```

And if that doesn't work, can you confirm whether it works with PySide2 directly?

**any_widget.py**

```python
import sys
from PySide2 import QtWidgets
app = QtWidgets.QApplication(sys.argv)
button = QtWidgets.QPushButton("Hello")
button.setFixedSize(400, 400)
button.show()
app.exec_()
```

**Comment by nyue** [comment]
Both does not work with Houdini's hython.

So I am guessing the way PySide2 is build for Houdini they did not include the platform plugins ?

Cheers

**Comment by mottosso** [comment]
> So I am guessing the way PySide2 is build for Houdini they did not include the platform plugins ?

Possibly, I think that's a question for the Houdini crowd.

**Comment by fredrikaverpil** [comment]
Perhaps this'll help: https://www.sidefx.com/forum/topic/49092/

**Comment by samhodge** [comment]
OK I take it nobody reported this to SideFX, I will open it up now, because it is currently blocking me.
