### ISSUE TITLE
[Question] Changing the preferred binding order from Python code

### ISSUE THREAD

**Issue by alby128** [mottosso/Qt.py#251]
I am aware of the QT_PREFERRED_BINDING environment variable, but I would like to know if it is possible to alter the order of bindings directly from python. I am currently using Qt.py through vendoring, so I know that I could also alter this manually by changing `default_order = ("PySide2", "PyQt5", "PySide", "PyQt4")`. Thanks.

**Comment by mottosso** [comment]
Certainly, you can modify the environment from within Python, and Qt.py will pick it up on first import.

```python
import os
os.environ["QT_PREFERRED_BINDING"] = os.pathsep.join(["PySide2", "PyQt5", "PySide", "PyQt4"])
import Qt
```

**Comment by alby128** [comment]
Great, thanks. However, I am not sure if this overrides the environment variables that the user may have set up before running my code. What I would like to do is to change the default binding order, without preventing the user to choose a preferred binding.

**Comment by mottosso** [comment]
Ah, yes you are right, this would override any existing variable.

How about asking for it first, and overriding if it doesn't already exist?

```python
import os

if "QT_PREFERRED_BINDING" not in os.environ:
  os.environ["QT_PREFERRED_BINDING"] = os.pathsep.join(
    ["PySide2", "PyQt5", "PySide", "PyQt4"]
  )

import Qt
```

**Comment by alby128** [comment]
That is perfect, thank you.

**Comment by mottosso** [comment]
You are most welcome.
