### ISSUE TITLE
Qt.QtGui.qRgba is missing

### ISSUE THREAD

**Issue by maty974** [mottosso/Qt.py#261]
Hi !

It seems that **QtGui.qRgba()** is missing in **Qt.py**.

```
Qt.__version__
'1.0.0'
```

```python
import Qt.QtGui
Qt.QtGui.qRgba()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'module' object has no attribute 'qRgba'
```
and using the PySide2 QtGui seems to work fine

```python
Qt._QtGui.qRgba
<built-in function qRgba>

Qt._QtGui.qRgba()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: qRgba expected 4 arguments, got 0
```

**Comment by mottosso** [comment]
Thanks @maty974, it looks like indeed it is missing.

Would you be able to submit a PR for it? Then the automatic tests would kick in and see if everything is allright across all bindings.

**Comment by fredrikaverpil** [comment]
If you upgrade to Qt.py 1.1.0b7, `qRgba` is available there:
https://github.com/mottosso/Qt.py/blob/master/Qt.py#L337

For future reference: when running `build_membership.sh`, the PySide/PyQt bindings members are compared and a `common_members.json` file is generated. The contents of this file is what we copy-paste into the `common_members` dictionary of Qt.py.
