### ISSUE TITLE
Missing QtPrintSupport

### ISSUE THREAD

**Issue by alexwidener** [mottosso/Qt.py#267]
Hi,

I am unable to find a reason for why this would be missing and am hoping somebody can enlighten me.

```
import Qt
print Qt.__binding__
print Qt.__binding_version__
from Qt import QtPrintSupport

PySide2
2.0.0~alpha0
# Error: ImportError: file <maya console> line 5: No module named QtPrintSupport # 
```

And in the same session:

```
import PySide2
from PySide2 import QtPrintSupport
QtPrintSupport
# Result: <module 'PySide2.QtPrintSupport' from '/[removed]/autodesk/maya/2018/maya/lib/python2.7/site-packages/PySide2/QtPrintSupport.so'> # 
```

I see the same result in PyQt4, where the member also exists.

Best,
Alex

**Comment by mottosso** [comment]
Thanks @alexwidener, looks like a missing member indeed. Welcome to submit a PR with it added to the list in the Qt.py file; the automatic tests will kick in to check that everything is A-OK.

**Comment by fredrikaverpil** [comment]
This seems odd to me. We have a membership comparison script which will compare all members across bindings...

Please let me verify this before merging anything.

**Comment by alexwidener** [comment]
https://travis-ci.org/mottosso/Qt.py/jobs/329962171#L570

Looks like PySide is the problem.

**Comment by MHendricks** [comment]
Yes, the classes in PyQt4/PySide are under QtGui, and they seem to be the same classes. It seems like all you need to do is add the correct values to the `_misplaced_members` dict. PySide in Maya 2016, and PySide2 in Maya 2017 both have the print classes. I haven't looked in other DCC's.

#268 I'm using QtPrintSupport as my example in this pull request, but that's because I noticed the bug updating some widgets that were printing using PyQt4. I agree that if QtPrintSupport can be added as default members of Qt.py it should be added.

**Comment by alexwidener** [comment]
Closed #269 in favor of #268

**Comment by MHendricks** [comment]
@fredrikaverpil unless you object, I'll update #268 to include QtPrintSupport in _common_members by default instead of requiring enabling using QtSiteConfig.

Without that update to `_reassign_misplaced_members` we can't add QtPrintSupport to Qt4 without modifying `_pyqt4` and `_pyside` to add the missing QtPrintSupport modules.

**Comment by fredrikaverpil** [comment]
Hm. I haven't really had time to investigate this but so it kind of seems like Adsk had some custom version of PySide(1), which we don't have in our test suite.

One thing that bothers me is that the list of common members is generated by build_membership.sh but this deviates from that. Which means that if we add QtPrintSupport now, we'll have to remember to add this in later manually whenever we re-run build_membetship.sh to generate a new list of common members (usually when we update the test suite to confirm with the next VFX platform and whatever commit of PySide2 is at around that same time).

I'm also worried that QtPrintSupport actually doesn't exist in other DCCs such as Nuke, Houdini etc... Has anyone tried to access this member in those apps?

**Comment by alexwidener** [comment]
Nuke 10.5v6 and Houdini 15:

```
from PySide.QtGui import QPrinter
# Result: QPrinter
# Result: <type 'PySide.QtGui.
```

**Comment by MHendricks** [comment]
I think QtPrintSupport is similar to how QtGui  was separated into QtGui and QtWidgets. How are you handling that?

All of these are tested on windows.
Houdini 16.5.323, Maya 2017, 3dsMax 2018:
```python
>>> from PySide2 import QtPrintSupport
>>> dir(QtPrintSupport)
['QAbstractPrintDialog', 'QPageSetupDialog', 'QPrintDialog', 'QPrintEngine', 'QPrintPreviewDialog', 'QPrintPreviewWidget', 'QPrinter', 'QPrinterInfo', '__doc__', '__file__', '__name__', '__package__']
```
Houdini 16.0.557, Maya 2016.0:
```python
>>> from PySide import QtGui
>>> for name in ['QAbstractPrintDialog', 'QPageSetupDialog', 'QPrintDialog', 'QPrintEngine', 'QPrintPreviewDialog', 'QPrintPreviewWidget', 'QPrinter', 'QPrinterInfo']: print getattr(QtGui, name)
<type 'PySide.QtGui.QAbstractPrintDialog'>
<type 'PySide.QtGui.QPageSetupDialog'>
<type 'PySide.QtGui.QPrintDialog'>
<type 'PySide.QtGui.QPrintEngine'>
<type 'PySide.QtGui.QPrintPreviewDialog'>
<type 'PySide.QtGui.QPrintPreviewWidget'>
<type 'PySide.QtGui.QPrinter'>
<type 'PySide.QtGui.QPrinterInfo'>
```

The Qt.py unit tests pass when adding QtPrintSupport to _common_members and updating _misplaced_members for Qt4 support. [`tests.test_membership()`](https://github.com/mottosso/Qt.py/blob/master/tests.py#L698)

**Comment by fredrikaverpil** [comment]
> I think QtPrintSupport is similar to how QtGui was separated into QtGui and QtWidgets. How are you handling that?

Ah, of course. That must be it. Then we will just have to put this into the build_membership.sh logic. Just like how I deal with the QtWidgets comparison..

**Comment by fredrikaverpil** [comment]
Edited my previous post! (on mobile..)

**Comment by MHendricks** [comment]
I'll update #268 so `copy_qtgui_to_qtwidgets` will copy QtGui into QtPrintSupport for Qt4. I assume that the compare function removes all the other QtGui widgets.


I haven't been able to find documentation on the specific motivations for splitting QtGui up, but I did find that PySide2.QtPrintSupport has zero missing types. https://wiki.qt.io/PySide2_Missing_Bindings#QtPrintSupport
Differences listed between PyQt4 and PyQt5 state: "PyQt4’s QtGui module has been split into PyQt5’s QtGui, QtPrintSupport and QtWidgets modules."
http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html#qtgui-module

**Comment by MHendricks** [comment]
I renamed `copy_qtgui_to_qtwidgets` to `copy_qtgui_to_modules`, and added QtPrintSupport in the same way QtWidgets was added.

I don't have a docker setup to test this, or a setup linux box. I was able to manually build bindings for PyQt4/PyQt5 and PySide(1) using membership.py on windows. The generated common members matched for QtPrintSupport.

@fredrikaverpil  Do you think we need to do a full, real test?

**Comment by fredrikaverpil** [comment]
> I renamed copy_qtgui_to_qtwidgets to copy_qtgui_to_modules, and added QtPrintSupport in the same way QtWidgets was added.

Looks good! 👍 

> @fredrikaverpil Do you think we need to do a full, real test?

I pulled down the #268 PR and successfully ran `build_membership.sh`. I copy-pasted the output of the common members produced here: https://gist.github.com/fredrikaverpil/2d871f078a0320d06702728874f1c446

So this is what Qt.py's `common_members` dict should contain.

Regarding running a test, you already investigated and made sure that this is how QtPrintSupport was remapped between Qt4 and Qt5 so I think we're fine.

**Comment by fredrikaverpil** [comment]
Actually, if you just import the Qt.py from the PR in e.g. Maya 2016 and in Maya 2018, this line should work in both these apps (haven't tried it myself):

    from Qt import QtPrintSupport

**Comment by fredrikaverpil** [comment]
Code to run in order to test `QtPrintSupport`:

    python -c "import sys; sys.path.insert(0, '/path/to/folder/containing-qt.py/'); from Qt import QtPrintSupport; print(QtPrintSupport)"

Running using docker container:

```bash
docker run --rm --interactive --tty -v $(pwd):/tmp/site-packages --entrypoint=/bin/bash fredrikaverpil/qt.py:201


$ export QT_PREFERRED_BINDING=PySide
$ python -c "import sys; sys.path.insert(0, '/tmp/site-packages'); from Qt import QtPrintSupport; print(QtPrintSupport)"
int(QtPrintSupport)"
Order: 'PySide'
Trying PySide
'QtCore.QItemSelectionRange' was missing.
<module 'Qt.QtPrintSupport' (built-in)>


$ export QT_PREFERRED_BINDING=PySide
$ python -c "import sys; sys.path.insert(0, '/tmp/site-packages'); from Qt import QtPrintSupport; print(QtPrintSupport)"
Order: 'PyQt4'
Trying PyQt4
'QtCore.QItemSelectionRange' was missing.
<module 'Qt.QtPrintSupport' (built-in)>


$ export QT_PREFERRED_BINDING=PySide2
$ python -c "import sys; sys.path.insert(0, '/tmp/site-packages'); from Qt import QtPrintSupport; print(QtPrintSupport)"
Order: 'PySide2'
Trying PySide2
<module 'Qt.QtPrintSupport' (built-in)>

$ export QT_PREFERRED_BINDING=PyQt5
$ python -c "import sys; sys.path.insert(0, '/tmp/site-packages'); from Qt import QtPrintSupport; print(QtPrintSupport)"
Order: 'PyQt5'
Trying PyQt5
<module 'Qt.QtPrintSupport' (built-in)>
```


So, all of this seems good to me. No need to run further tests, I guess?

**Comment by MHendricks** [comment]
```diff
diff --git a/Qt.py b/Qt.py
index c0edda9..d3f4942 100644
--- a/Qt.py
+++ b/Qt.py
@@ -110,7 +110,6 @@ _common_members = {
         "QGenericArgument",
         "QGenericReturnArgument",
         "QHistoryState",
-        "QItemSelectionRange",
         "QIODevice",
         "QLibraryInfo",
         "QLine",
@@ -622,9 +621,6 @@ _common_members = {
         "QWizard",
         "QWizardPage"
     ],
-    "QtX11Extras": [
-        "QX11Info"
-    ],
     "QtXml": [
         "QDomAttr",
         "QDomCDATASection",
```
That's the only difference between the PR's _common_members and the output you got. I think if we address them it should be a new issue and pull request as that could break backwards compatibility. 

Sounds like its ready to merge, I'll try my new merge powers tomorrow afternoon.

**Comment by fredrikaverpil** [comment]
Awesome @MHendricks - as far as I understand, we can close this issue?

I just pushed the v1.1.0 release!

**Comment by fredrikaverpil** [comment]
Oops - spoke too soon. Travis CI put me on queue... but soon; v1.1.0!
