### ISSUE TITLE
QApplication.type removed from Qt5

### ISSUE THREAD

**Issue by frueter** [mottosso/Qt.py#280]
Hi guys,

is this handled yet?:

> QCoreApplication::Type and QApplication::type() are removed. These Qt 3 legacy application types did not match the application types available in Qt 5. Use qobject_cast instead to dynamically find out the exact application type.

**Comment by mottosso** [comment]
Handled how? What are you expecting from Qt.py? An example would help.

**Comment by frueter** [comment]
Sorry, when I posted this I assumed PySide2 has equivalent ways of querying QApplication.type() but I have since learnt that it doesn't, so there is little you can do about it.
Sorry for the premature post.
