### ISSUE TITLE
PyInstaller cannot find QtCompat.loadUi

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#290]
A regular `print(QtCompat)` will give you this:

```
['QFileDialog', 'QHeaderView', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_cli', '_convert', 'getCppPointer', 'loadUi', 'load_ui', 'qInstallMessageHandler', 'setSectionResizeMode', 'translate', 'wrapInstance']
```

But if using [PyInstaller](https://github.com/pyinstaller/pyinstaller) to build/freeze an application out of your python script (such as an .exe), the same command results in the following (where `loadUi` and `load_ui` are missing):

```
['QFileDialog', 'QHeaderView', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_cli', '_convert', 'getCppPointer', 'qInstallMessageHandler', 'setSectionResizeMode', 'translate', 'wrapInstance']
```

This is with Qt.py version 1.1.0.

I haven't found a workaround so far... 😢

**Comment by fredrikaverpil** [comment]
Workaround:

```python
from PySide2 import QtXml  # Required by QtUiTools (or crash)
from PySide2 import QtUiTools  # Required for QtCompat.loadUi
from Qt import QtCompat
```

**Comment by mottosso** [comment]
> (where loadUi and load_ui are missing):

They aren't missing?

```
...CppPointer', 'loadUi', 'load_ui', 'qInstallMessageHandler', 'setSectionResizeMo...
```

I can see it in the line you added below.

**Comment by mottosso** [comment]
They *are* missing in the first snippet though, maybe it's the other way around? :)

**Comment by fredrikaverpil** [comment]
Oops!
Classic copy/paste mistake. Sorry. I'll switch those two lines around.

**Comment by fredrikaverpil** [comment]
Another workaround, using a PyInstaller [hook](https://pythonhosted.org/PyInstaller/hooks.html). Add a hook `hook-Qt.py` with contents:

```python
hiddenimports = ["PySide2.QtXml", "PySide2.QtUiTools", "Qt.QtCompat"]
```

**Comment by fredrikaverpil** [comment]
This seems stale.
