### ISSUE TITLE
Custom Widget not supported

### ISSUE THREAD

**Issue by michimussato** [mottosso/Qt.py#295]
https://github.com/mottosso/Qt.py/blob/cc5e730cc3e5e901a3bd1d4df343006ebd77e3e0/Qt.py#L894

We have:

```
class ManagerTable(QtWidgets.QTableView)
```
and

```
class AssetTable(ManagerTable)
```

This throws an error `Custom widget ManagerTable not supported`.

Modifications I did to `Qt.py`:

```
                try:
                    widget = Qt._QtUiTools.QUiLoader.createWidget(self,
                                                                  class_name,
                                                                  parent,
                                                                  name)

                except Exception:
                    raise Exception("Custom widget '%s' not supported"
                                    % class_name)
```

**Comment by mottosso** [comment]
Thanks @michimussato, would it be possible to put your modification into a PR? That way, our automated tests will take it for a spin and make sure it runs on all bindings, platforms and Python interpreters.

**Comment by michimussato** [comment]
Sorry. My changes do not do the trick.

**Comment by mottosso** [comment]
That's allright; once it's in a PR, we can start iterating on a solution that does the trick, where every change is being run through the same series of tests. Once the tests pass, odds are we've got a winner.

**Comment by YKdvd** [comment]
It looks like the current state of master (1.2.0.b3) has solved this?  I have a Designer .ui file that I load through QtCompat.loadUi(), which "promotes" a TableView object to a custom subclass MyTableView.  This works with my Python 2.7/PyQt4 setup, but when I run it inside Maya 2016 (pyside) or Maya2018 (pyside2), I get the above custom widget unsupported error. When I bring in the current Qt.py code, it works (at least superficially).

Is there any timeline for a 1.2.0 release to PyPi?  It would be nice to be able to do simple "pip install" to get this.

**Comment by mottosso** [comment]
> Is there any timeline for a 1.2.0 release to PyPi? It would be nice to be able to do simple "pip install" to get this.

This isn't working for you?

```bash
$ pip install Qt.py==1.2.0.b3
```
