### ISSUE TITLE
TypeError: 'PySide2.QtWidgets.QBoxLayout.addWidget' called with wrong argument types

### ISSUE THREAD

**Issue by albertosottile** [mottosso/Qt.py#308]
After the recent update to `pyside2 5.12.1` I got this error in several parts of our application:

`
  File "/Users/alberto/syncplay/syncplay/ui/GuiConfiguration.py", line 1112, in addMessageTab
    self.languageLayout.addWidget(self.languageLabel, 1, 0)
TypeError: 'PySide2.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QBoxLayout.addWidget(QLabel, int, int)
Supported signatures:
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget, int = 0, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget)
`

There was probably a change in `qt 5.12.1` about the addWidget implementations. I know that I could fix it manually in the app code, but is there a way for Qt.py for avoiding that and address this change in the shim instead? Thanks.

**Comment by bpabel** [comment]
Technically, even the docs for Qt4 say the type of the last value should be `Qt.Alignment`, which is the same as for Qt5.  Using Qt.py, you would still need to modify your code to pass Qt5-compatible code, which in this case would be 

    layout.addWidget(widget, 0, QtCore.Qt.Alignment())

Which also works in Qt4, so Qt.py (or your own code) doesn't actually have to do any conversion or shimming as long as you're using Qt5 syntax (which is technically the same as the the Qt4 syntax, except Qt4 appears to also support sending through integers, too).

**Comment by albertosottile** [comment]
The idea was to reimplement a method that accepted `(QLabel, int, int)` as arguments, but I recognize that it will not respect the actual Qt5 syntax, even though it worked with PySide 1.x and PySide2 up to 5.12.0. 

We are currently adapting our codebase to the new syntax. You can close this issue.
