### ISSUE TITLE
License is being installed to `/usr/LICENSE`

### ISSUE THREAD

**Issue by FFY00** [mottosso/Qt.py#309]
```
python setup.py build
python setup.py install --optimize=1 --skip-build
```

This generates a `LICENSE` file in `/usr` which is super weird.

**Comment by mottosso** [comment]
Haha, yes that does sound wierd. Must be some `pip` behavior.

Does it still happen if you remove [this line](https://github.com/mottosso/Qt.py/blob/1f7e1cad4eba3ddd34433df289b28a899537d029/setup.py#L34)?

**Comment by FFY00** [comment]
Nop, as we expected.

```
usr
 ├─LICENSE
 └─lib
    └─python3.7
       └─site-packages
          ├─Qt.py
          ├─Qt.py-1.2.0b3-py3.7.egg-info
          │  ├─PKG-INFO
          │  ├─SOURCES.txt
          │  ├─dependency_links.txt
          │  ├─not-zip-safe
          │  └─top_level.txt
          └─__pycache__
             ├─Qt.cpython-37.opt-1.pyc
             └─Qt.cpython-37.pyc
```

**Comment by mottosso** [comment]
I'm having trouble reproducing this under Ubuntu 16.

I do however spot a message with regards to he License file.

```
warning: install_data: setup script did not provide a directory for 'LICENSE' -- installing right in 'build/bdist.linux-x86_64/egg'
```

Here's the full stack.

```bash
/Qt.py# python setup.py install --optimize=1 --skip-build
/usr/lib/python2.7/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing '1.2.0.b3' to '1.2.0b3'
  normalized_version,
running install
running bdist_egg
running egg_info
writing Qt.py.egg-info/PKG-INFO
writing top-level names to Qt.py.egg-info/top_level.txt
writing dependency_links to Qt.py.egg-info/dependency_links.txt
reading manifest file 'Qt.py.egg-info/SOURCES.txt'
writing manifest file 'Qt.py.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/Qt.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/Qt.py to Qt.pyc
writing byte-compilation script '/tmp/tmpoJvkdf.py'
/usr/bin/python -O /tmp/tmpoJvkdf.py
removing /tmp/tmpoJvkdf.py
installing package data to build/bdist.linux-x86_64/egg
running install_data
warning: install_data: setup script did not provide a directory for 'LICENSE' -- installing right in 'build/bdist.linux-x86_64/egg'

copying LICENSE -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Qt.py.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Qt.py.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Qt.py.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Qt.py.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Qt.py.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/Qt.py-1.2.0b3-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Qt.py-1.2.0b3-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/Qt.py-1.2.0b3-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/Qt.py-1.2.0b3-py2.7.egg
Extracting Qt.py-1.2.0b3-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Qt.py 1.2.0b3 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/Qt.py-1.2.0b3-py2.7.egg
Processing dependencies for Qt.py==1.2.0b3
Finished processing dependencies for Qt.py==1.2.0b3
root@af4ce03431b8:/Qt.py# ls /usr/
bin  games  include  lib  local  sbin  share  src
root@af4ce03431b8:/Qt.py#
```

**Comment by FFY00** [comment]
Here my build process: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-qt.py

As you see I have to manually remove the `LICENSE` file.

**Comment by mottosso** [comment]
There's actually no need for that file to even exist. The licence has since been [embedded into the Python module](https://github.com/mottosso/Qt.py/blob/master/Qt.py#L1780) and remains around mostly to let GitHub fill in that nice little field in its GUI.

![image](https://user-images.githubusercontent.com/2152766/53289174-8ea98680-378a-11e9-8d99-be9229370a82.png)

I'd be happy to either remove this file or remove any reference to it [from the `setup.py`](https://github.com/mottosso/Qt.py/blob/1f7e1cad4eba3ddd34433df289b28a899537d029/setup.py#L34). Did you say you tried that, and it still happened? That would be sparta. I mean madness.

Alternatively, if it helps, the only relevant file for any distribution is that `Qt.py` file itself; so if your build-system permits it, you could merely download that file and skip any build/install step provided by setuptools.

**Comment by CAM-Gerlach** [comment]
Just FYI, including `LICENSE` in `data_files` is likely the issue, or at the very least an issue; `data_files` is a a long deprecated, discouraged and unsafe way of distributing files outside the package tree that will eventually be fully removed, whereas the `license_files`, `license_file` and `MANIFEST.in` (in that order) are all much more appropriate solutions, never mind that reasonably modern packaging tools (thanks to a feature I helped add) will include `LICENSE` as a `license_file` automatically. So I suggest simply removing it, as there's no need for it anymore and it can only cause problems.

**Comment by mottosso** [comment]
Done, thanks.
