### ISSUE TITLE
pip search doesn't show Qt.py

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#31]
For some reason, this doesn't return anything:

    pip search Qt.py

Sorry, I wish I could be of more help. I'm unfamiliar with how to set up pip (although I'd like to learn).

**Comment by mottosso** [comment]
It can take a while (weeks..) for PyPI to update it's registers. It's terrible.

**Comment by fredrikaverpil** [comment]
Ahh.
