### ISSUE TITLE
Maya Hangs on Qt.py import

### ISSUE THREAD

**Issue by Nixellion** [mottosso/Qt.py#313]
Hello! A couple of users of my BroDynamics plugin have an issue with Maya hanging on plugin load. Issue seems to be with less than 10% of users but it only makes it more weird one to debug.

Just now I was allowed to connect to the affected machine with TeamViewer and run some tests on it. I managed to narrow it all down to attempts to import Qt.py and related modules.

In my plugin I have the following structure:

```
+-- Project
|     +-- module1
|          +--...
|     +-- module1
|          +--...
|     +--plug-ins
|          +--project.py
|     +-- core
|             +-- myqt
|                   +-- vendor
|                         +-- Qt.py
|                   +-- my_widgets.py
+--__init__.py
+--foo.py
+--bar.py
```

and Maya hangs if I try to `from Project.core.myqt.vendor import Qt` but if I put Qt.py into the root of the Project folder and run `from Project import Qt` it works fine.

**Any ideas what may be happening here?** Right now I'm going to move it out of that folder into root and refactor the whole project, but I wonder if it's even gonna solve the problem. 

I'm not sure what else may be wrong, I tried running all other commands and they work fine. I also don't think it has to do with any import loops. I did try hard to avoid them, but even if I didn't - I mean it works for majority of users, and only a few have this issue. 

As for diversity of users, I'm talking hundreds over the world on different PCs and OSes - Windows, Mac, Linux, and different hardware. Intel Xeon, however, seems to show up most when it comes to this issue. But this may be just a wild guess.

Thanks for your time and attention!

**Comment by mottosso** [comment]
Hi @Nixellion,

Hard to say, but I've seen this happen is Qt.py finds a binding not compatible with Maya; e.g. a PyQt5 binding installed for the system-wide version of Python. Or PySide(1) being picked up from Maya 2018.

To find out, on the machine with the problem, see if you can get some sense of which is being picked up.

```python
import Qt
print(Qt.__binding__)`
# PyQt5
```

Once you have that, import it directly and see where it is.

```python
import PyQt5
print(PyQt5)
<module 'PyQt5' from 'C:\\Python36\\lib\\site-packages\\PyQt5\\__init__.py'>
```

If what you're seeing is something like the above, where Qt.py has found a binding not shipped with or built for the version of Maya, then that's likely your problem.

If what you're seeing is `PySide2` and that it resides in e.g..

```python
<module 'PySide2' from 'C:\Program Files\Autodesk\Maya2018\Python\lib\site-packages\PySide2\__init__.pyc'>
```

Then the problem is elsewhere.

> Right now I'm going to move it out of that folder into root and refactor the whole project, but I wonder if it's even gonna solve the problem.

I wouldn't count on it. Qt.py doesn't do anything that can affect a system; it's merely mapping variable names from one place to another. Only the DLLs of a binding could cause this kind of havok.

> from Project.core.myqt.vendor import Qt

There is one other thing you could try and make sure of. When you do a globally referenced import like that, it's possible your users have multiple versions of your software on their machine and that it picks up an older version from within a newer one.

A safer alternative is to do relative imports, e.g. `from .core.myqt.vendor import Qt`

Hope it helps!

**Comment by Nixellion** [comment]
Hi, @mottosso , thanks for reply!

I'll try to test it out, however I do only have limited access to their workstation, can't poke around too much.

However, you suggest this:

> To find out, on the machine with the problem, see if you can get some sense of which is being picked up.

I'm not sure if this is the case, because, as I mentioned it does work if it's located under `project\qt.py` but it does hang if I move it under `project\core\myqt\vendor\qt.py`. I also don't use `import Qt` so it can't pick up the wrong Qt.py installation. I use `from project.core.myqt.vendor.qt import QtWidgets` and the like.

I will, however, make sure to still run this test.

When I use this: `from project.core.myqt.vendor.Qt import QtWidgets` does Python import modules mentioned? Does it import any of the submodules? Maybe the problem is in some other module residing under `myqt` that gets imported when I try to import qt.py ? However I don't see anything that could cause that, all that's there are just class declarations for windows and some function declarations and some imports of mayamixin and the like... Nothing that should cause it to hang. And again, it works for over 90% of users O,O so frustrating.

> There is one other thing you could try and make sure of. When you do a globally referenced import like that, it's possible your users have multiple versions of your software on their machine and that it picks up an older version from within a newer one.

Yes, sorry for confusion, I don't actually do an import like that, it's just an example. In my project I use `from project.core.myqt.vendor.Qt import QtWidgets, QtCore, QtGui`. I also just recently moved away from "star" imports for Qt and refactored anything into using QtWidgets, QtCore and QtGui explicitly.

Also yes, the problem of multiple versions of my plugin in maya's python paths arises now and then, but here I'm talking about a controlled environment, and I made sure that the right one gets imported. Spent over an hour in hardcore debugging mode commenting out lines and adding print statements and importing modules separately to find out where the root of the problem may be.


If you have any other general ideas why this may happen with Maya or just Python please advise.

And thanks again for your help.

**Comment by mottosso** [comment]
Ok, at this point I would start removing lines from within Qt.py until it stops crashing, or adding until it starts crashing.

For example, for each of these, does it still crash?

1. Remove all lines, leave an empty Qt.py file
2. If not, remove all lines, add a `from PySide2 import QtCore, QtWidgets, QtGui`
3. If not, remove all references to `sip` or `shiboken`, these are also (separate) compiled libraries that could cause trouble
4. If not, remove all members of the `_common_members` dictionary, that should leave you with an empty `QtCore` etc.

And so forth. I wouldn't be surprised if it still crashes on (1), in which case there's something other than Qt.py going on.

**Comment by Nixellion** [comment]
>     1. Remove all lines, leave an empty Qt.py file

That's genius, should've tried that myself. I did it for some other files but did not think of doing it with Qt.py. 

Will try all of the above. I too have a feeling it may still crash with empty Qt.py file. 

Thanks! I will report back with results.

**Comment by Nixellion** [comment]
Hi again, so finally had time to get back to this issue and run some more tests.

I don't think it's Qt.py anymore, I can import it safely now. It's just that some other __init__.py file was importing another file in the process, the one that's causing the issues.

I narrowed it down to one file, where I define base classes for windows, dockable, non dockable, etc, for use in other places. 

I tried adding print statements here and there, but on import it does not print anything at all.
Will now start removing lines from it to narrow it down further.

**Comment by Nixellion** [comment]
Hah... Found it. I think.

Running this code inside maya on the affected machines (even just pasting it into Script Editor) hangs it:

```
print "Webview depending on version of PySide is different"
try:
    from PySide2.QtWebEngineWidgets import QWebEngineView as WebView

    print("Using QWebEngineView as WebView")
except:
    try:
        from PySide.QtWebKit import QWebView as WebView

        print ("Using QWebView as WebView")

    except:
        WebView = QtWidgets.QTextBrowser
        print ("Using QtCore.QTextBrowser as WebView")
```

**Comment by Nixellion** [comment]
Finally the issue was resolved.

Some anti-malware software they use was somehow blocking or breaking `import PySide2.QtWebEngineWidgets` command. Once they turned it off everything worked, and they said they tweaked it somehow to not interfere with `QtWebEngineWidgets`. 

They did not yet answer what software it was or what they tweaked exactly to make it work.

**Comment by mottosso** [comment]
Thanks for the updates @Nixellion

**Comment by tjpdigital** [comment]
> If what you're seeing is something like the above, where Qt.py has found a binding not shipped with or built for the version of Maya, then that's likely your problem.

What do you do if  this is the casse?  Is there a way to get around this other than uninstalling the pyside module from Python27/Scripts?

**Comment by mottosso** [comment]
Have a look at https://github.com/mottosso/Qt.py#override-preferred-choice

**Comment by tjpdigital** [comment]
Thanks for the link!  I'm hoping you can clarify something.  The Override Preference is to tell Qt you'd like to access PySide before PySide2 or only look for Qt4 and nothing else, is that correct? 

Can you leverage that to address the situation you called out where PySide is the preferred but its attempting to load PySide from Python27/Scripts/ instead of Autodesk/Maya/ ?

**Comment by mottosso** [comment]
Unfortunately not. Not even Python is able to distinguish between those. It also looks at its own `sys.path` one directory at a time in the order they appear for anything you import. So if PySide at `Python27/Scripts` comes before `Maya/`, then that's what you'll get.

You could however modify `sys.path` before attempting to import Qt.py. Brute force would be to completely replace it with the path you want, `import Qt.py`, and then restore it.

**Comment by tjpdigital** [comment]
Ok cool,  I understand.  Thanks for clarifying.  I had the thought of trying to monkey with the sys.path as well!  Might play with that.  

I can't speak to the robustness of this workaround but I've found that uninstalling pyside from python allows Qt starts working as expected.  That makes sense.  But I then reinstalled pyside and Qt continues to work.  I assume the path was reordered based on their install order. 

I will need to come up with a nice way to account for this across multiple machines as some don't have this ordering problem and some do.

**Comment by Nixellion** [comment]
A headsup, with hopes that maybe someone found a solution - importing qtwebenginewidgets still has a chance of hanging Maya and as I now look for information about it - not just Maya but any Qt application. Still can't find for any reasons. Windows RESMON says that process is waiting for finishing of network IO.

**Comment by mottosso** [comment]
Is this related to Qt.py? I don't think it's available in Qt.py, because it's Qt 5-only. Better ask on the [Qt forums](https://forum.qt.io/).

**Comment by Nixellion** [comment]
No, just thought to follow up on the issue. Maybe not directly but it still may be useful for Qt.py users.
