### ISSUE TITLE
loadUi acting funny in maya...

### ISSUE THREAD

**Issue by mangopipeline** [mottosso/Qt.py#315]
my guess is that i'm doing something wrong here...
maybe someone here could shine a lite as i'm sure i own't be the only one....

 try the following code snippet (ui file attached)
Basically the just embeds into the wain window...
Im currently inheriting from QWidget but I've also tried inheriting from QDialog 

```
from Qt import QtWidgets, QtCompat
import maya.OpenMayaUI as apiUI

UI = r'c:\temp\test.ui'

class MyGui(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super(MyGui,self).__init__(parent)
        QtCompat.loadUi(UI,self)
        
if __name__ == '__main__':
    PTR = long(apiUI.MQtUtil.mainWindow())
    MAYAWIN = QtCompat.wrapInstance(PTR, QtWidgets.QMainWindow)
    MGUI = MyGui(parent=MAYAWIN)
    MGUI.show()
```
in pySide and pySide2 i was using the base,form inheritance design, PyQt seems to struggle with this a bit... so i'm trying to move over to using the QCompat module...

cheers,
Los.

[test.zip](https://github.com/mottosso/Qt.py/files/2989018/test.zip)

**Comment by mangopipeline** [comment]
i'm attaching a screen grab of what i'm seeing on my end...
maya 2016....

![image](https://user-images.githubusercontent.com/5678056/54699534-32beed00-4aff-11e9-8ffd-75dc92be0ef9.png)

**Comment by bpabel** [comment]
I think you just need to wrap your `QWidget` in a `QDialog` or `QMainWindow`.  If you hadn't included the maya window as a parent, I think Qt will automatically wrap a bare `QWidget` in a `QDialog`, which is what you might have seen if you were testing this outside of Maya.

**Comment by mottosso** [comment]
Yeah, I don't see anything odd going on here. How else would you embed a QWidget into an existing Window?

What you're looking for is either QDialog, or to set the WindowFlags for your QWidget such that it creates its own window.

**Comment by mangopipeline** [comment]
> 
> 
> Yeah, I don't see anything odd going on here. How else would you embed a QWidget into an existing Window?
> 
> What you're looking for is either QDialog, or to set the WindowFlags for your QWidget such that it creates its own window.

I guess my confusion is from using loadUiType instead of loadUi...

i imagined that loadUI would be a compatibility mode for loadUiType  between PySide and PyQt...

Pyside uic does not offer a loadUiType method so folks often implemented it them selfs....
it also doesn't help that pyside didn't always ship with pysideuic

here's what pyside uic loadUiType looks like...
https://gist.github.com/mstuttgart/bc246b25b8e0f7edd743

maybe loadUiType is allready in the QtCompat and I just didn't see it?
here's how loadUiType work if you haven't played with it...

it's a much better way to load ui files as it support Dialogs and MainWindows with any extra wrapping...
just inherits it properly....

`
FORM,BASE=QtCompat.loadUiType("myform.ui")
class MyGui(FORM,BASE):
   def __init__(parent=None):
       super(MyGui,self).__init__(parent)
       self.setupUi(self)

if __name == '__main__':
    PTR = long(apiUI.MQtUtil.mainWindow())
    MAYAWIN = QtCompat.wrapInstance(PTR, QtWidgets.QMainWindow)
    MGUI = MyGui(parent=MAYAWIN)
    MGUI.show()`
`

**Comment by mangopipeline** [comment]
by the way this is how  I'll probably get around it for now...
https://github.com/mangopipeline/Qtpy_load_ui_type/blob/master/load_ui_type.py

it's not perfect as it's not python3 compliant due to changes in strings vs bit string stuff that i have not wrapped my head around yet...

```

from load_ui_type import loadUiType
BASE,FORM  = loadUiType('mygui.ui')
```
