### ISSUE TITLE
QMediaPlayer missing from QtMultimedia

### ISSUE THREAD

**Issue by assumptionsoup** [mottosso/Qt.py#318]
This appears to be missing?

This works fine:
```
from PySide2.QtMultimedia import QMediaPlayer
```

This raises an attribute error:
```
from Qt import QtMultimedia
QtMultimedia.QMediaPlayer
```

**Comment by fredrikaverpil** [comment]
It's because QtMultimedia does not exist in PySide(1)/PyQt4.

The original aim of Qt.py was to provide a cross-binding compatibility so that devs would easily spot errors which would fail under a different binding than the one being used by the dev.

**Comment by mottosso** [comment]
That's right. If you don't need to support Qt 4, see [Qt5.py](https://github.com/mottosso/Qt5.py).

**Comment by assumptionsoup** [comment]
Thanks, I wasn't completely aware that Qt.py was targeting Qt4 compatibility over Qt5 given the layout of the modules, but that makes a lot of sense. I'll be sure to switch to Qt5.py when I can drop support for Qt4.
