### ISSUE TITLE
Travis-CI: register new versions with PyPI

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#32]
`pip install -U Qt.py` returns version 0.2.2 for me (although 0.2.3 is available).

I'm very unfamiliar with how pip works and I've never distributed anything using it.

Do you have to perform any manual labour in order to get the newer 0.2.3 out onto PyPi?
I was under the impression that the setup.py was supposed to handle that?

I had to curl down the newest Qt.py from the github repo today since I wasn't able to fetch it via pip.

**Comment by mottosso** [comment]
In a nutshell, it works like this.

- Create a `setup.py`, with project name and other metadata
- Register a name on PyPI (`python setup.py` register`)
- Upload to PyPI (`python setup.py sdist upload`)

Here's the shortest guide I could find.

- http://peterdowns.com/posts/first-time-with-pypi.html

There are such a vast amounts of options available for producing these distributions, so most guides are very complicated.

> Do you have to perform any manual labour in order to get the newer 0.2.3 out onto PyPi?
I was under the impression that the setup.py was supposed to handle that?

Yes, you need to upload it yourself. I've been doing that manually so far, but you can also tell Travis-CI to do it automatically whenever a new GitHub release is made. pyblish-base does that, for example. 

- https://github.com/pyblish/pyblish-base/blob/master/.travis.yml#L13

I'll set that up here as well. Then all we need to do is tag a release and it'll get uploaded automatically.

- https://github.com/mottosso/Qt.py/releases

I've uploaded 0.2.3 manually for now, so updating should work again.

**Comment by fredrikaverpil** [comment]
> you can also tell Travis-CI to do it automatically whenever a new GitHub release is made

Ooh, nice. That we should do. I'm renaming this issue then, so we can keep track of the Travis-CI implementation.
