### ISSUE TITLE
support for `QSortFilterProxyModel.recursiveFilteringEnabled` property added in Qt5?

### ISSUE THREAD

**Issue by MagicRedDeer** [mottosso/Qt.py#325]
This one might be a candidate for the QtCompat module.

A new property [recursiveFilteringEnabled](https://doc.qt.io/qt-5/qsortfilterproxymodel.html#recursiveFilteringEnabled-prop) was added to `QSortFilterProxyModel` in Qt5. This behaviour can be achieved with Qt4 by overriding the `filterAcceptsRow` as discussed [here](https://stackoverflow.com/questions/250890/using-qsortfilterproxymodel-with-a-tree-model). 

Following is a python port that seems to do the same thing.

```python
class RecursiveFilterModel(QtCore.QSortFilterProxyModel):
    ''' A Proxy Model for tree view that shows parent item if one of the
    children matches
    '''

    def filterAcceptsRow(self, source_row, source_parent, orig=False):
        ''' Override function to accept row if any of the children or
        descendants is acceptable
        '''

        if not self.filterRegExp().isEmpty():
            source_index = self.sourceModel().index(
                    source_row, self.filterKeyColumn(), source_parent)
            if source_index.isValid():
                for i in range(self.sourceModel().rowCount(source_index)):
                    if self.filterAcceptsRow(i, source_index, orig=True):
                        return True
                key = self.sourceModel().data(source_index, self.filterRole())
                return self.filterRegExp().indexIn(key) >= 0
        return super(RecursiveFilterModel, self).filterAcceptsRow(
                source_row, source_parent)
```

Maybe this model with the property can be added to QtCompat as an alternative.

**Comment by mottosso** [comment]
Thanks for sharing this, it will enable folks to search and discover this solution for their own projects. I'm not sure it has a place natively in Qt.py though, simply because there's no ceiling to how much we could actually include until eventually the Qt.py file is in the megabyte range with stuff few people use.

Feel free to reopen if you or anyone feels otherwise.
