### ISSUE TITLE
Cannot import QWindow from QtGui

### ISSUE THREAD

**Issue by bob-white** [mottosso/Qt.py#326]
```python
from Qt.QtGui import QWindow, QKeyEvent, QCloseEvent
ImportError: cannot import name 'QWindow' from 'Qt.QtGui' (unknown location)
```

Works fine if I go back to:
```python
from PySide2.QtGui import QWindow, QKeyEvent, QCloseEvent
```

**Comment by mottosso** [comment]
QWindow isn't available in Qt 4, sorry. :(

- https://doc.qt.io/qt-5/qwindow.html

**Comment by bob-white** [comment]
Ah. Well that is frustrating. Though I guess the curse of being a compatibility layer.

**Comment by mottosso** [comment]
Indeed. But have a look at https://github.com/mottosso/Qt5.py if all you need is Qt 5

**Comment by bob-white** [comment]
Excellent.
