### ISSUE TITLE
Not support Nuke12 

### ISSUE THREAD

**Issue by binzb** [mottosso/Qt.py#327]
Not support Nuke12  
Update please 
thx

**Comment by mottosso** [comment]
Thanks for reporting this @binzb. Would it be possible to post the error you get? A screenshot would be good, a stacktrace or error message would be better.

**Comment by binzb** [comment]
> Thanks for reporting this @binzb. Would it be possible to post the error you get? A screenshot would be good, a stacktrace or error message would be better.

line 1772
raise ImportError("No QT binding were found")

**Comment by mottosso** [comment]
Oh wow, that's interesting. It's possible this isn't a problem with Qt.py, but a problem of environment variables.

Can you try this?

```python
import PySide2
```

Alternatively, this:

```python
import PyQt5
import PyQt4
import PySide
```

What is the output?

**Comment by binzb** [comment]
Solved , it is a problem of environment variables.
thx
