### ISSUE TITLE
missing QtCore.SIGNAL?

### ISSUE THREAD

**Issue by lawschlosser** [mottosso/Qt.py#328]
Not sure if it's an intentional decision, but the `QtCore.SIGNAL` function is missing (not to be confused with the `QtCore.Signal` class).  Though the `SIGNAL` function is typically used for "old style" connections, it is also useful (essential?) in order to make connections to signals that don't exist (at the time).

### Environment
```bash
python --version
# Python 2.7.15+

pip install pyside2 qt.py

pip freeze
# PySide2==5.13.1
# Qt.py==1.2.1
# shiboken2==5.13.1
```
### Qt.py behavior
```bash
python -c "from Qt import QtCore; print QtCore.SIGNAL"     
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'SIGNAL'
```
### PySide2/Expected behavior
```bash
python -c "from PySide2 import QtCore; print QtCore.SIGNAL"
<built-in function SIGNAL>
```

Btw, I appreciate the effort you guys have put behind this project.  It's been a life saver.

**Comment by mottosso** [comment]
Hi @lawschlosser, thanks for reporting this. It was indeed an intentional exclusion, but it sounds like it may have been based on misinformation. As far as I knew, `SIGNAL` was deprecated, completely superceeded by `.connect()`.

If that's not the case, then it should certainly be included, assuming it does in fact work the same across both Qt 4 and 5.

Would it be possible to share an example, and better yet, to actually add it along with a test? The test would trigger CI which would run on each binding with appropriate versions of each.

**Comment by lawschlosser** [comment]
@mottosso The oldstyle convention (using `SIGNAL`), vs the new style (`Signal`) is somewhat akin to the difference between setting an attribute via `setattr(object, "attr", value)`  vs `object.attr=value`.  The ability to set an attribute by using the attribute's name is still powerful.
Additionally, and perhaps more importantly, the ability for an object be able to emit any signal (without fist defining that signal as an attribute on itself) is also really useful.

For example, you could have a QObject dynamically emit any signal (perhaps based upon a provided argument):

```python3
from PySide2 import QtCore

class Emitter(QtCore.QObject):
   
    def emitSignature(self, signature, arg):
        '''
        Emit a signal using the given signature (str).
        '''
        self.emit(QtCore.SIGNAL(signature), arg)


def slot_function(arg):
    print(arg)

```
we can then connect any arbitrary signal to the slot function
```python3
import uuid

# create a signature using any random character (but expects a str arg when emitted)
dynamic_signature = "%s(QString)" % uuid.uuid4()

# create our emitter object and connect our dynamic signature to the our slot function
emitter = Emitter()
emitter.connect(QtCore.SIGNAL(dynamic_signature), slot_function)

# Emit a signal using our dynamic signature
emitter.emitSignature(dynamic_signature, "my message")
# results in printing "my message"

# Try emitting a different signal (that isn't connected to anything)
emitter.emitSignature("mylonelysignal()", "my message")
# nothing is printed because that signal wasn't connected to a slot.
```
Perhaps there are other ways to achieve this without using the `SIGNAL` function, but I haven't stumbled upon them.

When I get an opportunity, I'll look into creating a test.  thanks

**Comment by mottosso** [comment]
Had a quick look at this, and it looks like `SIGNAL` is not part of PyQt5 (only PySide2 and PySide2, from what I can tell). Which means that if we introduce it to Qt.py, code written would work differently if the bindings are PyQt versus PySide, so we probably can't include it.

Feel free to reopen this is anything changes.
