### ISSUE TITLE
Missing QtWidgets.QOpenGLWidget

### ISSUE THREAD

**Issue by sylvainberger** [mottosso/Qt.py#341]
The QQOpenGLWidget class is not available in QWidgets

The workaround is to import it from PySide2 directly
from PySide2.QtWidgets import QOpenGLWidget

It would be nice to have it exposed in the Qt.QWidgets module

Thanks

**Comment by mottosso** [comment]
It's only available to Qt 5; for anything to qualify for Qt.py, it must be available in all bindings simultaneously, including PySide(1).

- https://doc.qt.io/qt-5/qopenglwidget.html

> Note "Since: Qt 5.4"

**Comment by mottosso** [comment]
See [Qt5.py](https://github.com/mottosso/Qt5.py) if you no longer need support for Qt 4.

**Comment by sylvainberger** [comment]
Thanks
I never realized that this logic was present in qt.py
It makes total sense. 
I will use qt5.py instead 
Cheers
