### ISSUE TITLE
loadUi BUG

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [mottosso/Qt.py#344]
When I promote a custom widget with different \_\_init__ paramters ，it will hit a Bug here

![01](https://user-images.githubusercontent.com/40897360/87875613-07a32100-ca05-11ea-92a1-afcc39f0b092.png)

My first parameter isn't the parent object ， how to fix is easy.

```python
widget = self.custom_widgets[class_name](parent=parent)
```

**Comment by mottosso** [comment]
Thanks for reporting this @FXTD-ODYSSEY, and sorry for the late reply, holiday time over here.

Would you like to [edit this](https://github.com/mottosso/Qt.py/edit/master/Qt.py) and submit a pull-request? That way, the automated tests will kick in and double-check everything is A-OK.
