### ISSUE TITLE
Import QJsonDocument, QJsonParseError from Qt.QtCore is failure

### ISSUE THREAD

**Issue by moebiusever** [mottosso/Qt.py#347]
Hello, I can't import QJsonDocument, QJsonParseError which PyQt5 as the backend, the Python version is 3.6
when
`from Qt.QtCore import QJsonDocument, QJsonParseError`
it reports:
```
In [10]: from Qt.QtCore import QJsonDocument, QJsonParseError
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-10-95356b5689b4> in <module>
----> 1 from Qt.QtCore import QJsonDocument, QJsonParseError

ImportError: cannot import name 'QJsonDocument'
```

**Comment by mottosso** [comment]
Hi @moebiusever, thanks for the report. That's a Qt5-only class, https://doc.qt.io/qt-5/qjsondocument.html which would break any app still using Qt 4.

See [Qt5.py](https://github.com/mottosso/Qt5.py) if you no longer need to support Qt 4.
