### ISSUE TITLE
QT-Py internal NEOPixel 

### ISSUE THREAD

**Issue by Jumpin-JackFlash** [mottosso/Qt.py#356]
Hi,
 I have been trying to run the example put out on ADAFruit by Kattni but I have not had any suceess getting the internal LED to change colors. I have loaded the two files into my lib folder as well. I believe the program maybe missing an import adafruit_pypixel buf and maybe something else. Can I get some help NEWB, example as follows;

"""
Blink example for boards with ONLY a NeoPixel LED (e.g. without a built-in red LED).
Includes QT Py and various Trinkeys.
Requires two libraries from the Adafruit CircuitPython Library Bundle. Download the bundle
from circuitpython.org/libraries and copy the following files to your CIRCUITPY/lib folder:
* neopixel.mpy
* adafruit_pypixelbuf.mpy
Once the libraries are copied, save this file as code.py to your CIRCUITPY drive to run it.
"""
import time
import board
import neopixel

pixels = neopixel.NeoPixel(board.NEOPIXEL, 1)

while True:
    pixels.fill((255, 0, 0))
    time.sleep(0.5)
    pixels.fill((0, 0, 0))
    time.sleep(0.5)

**Comment by mottosso** [comment]
What on earth are you on about? How is this about Qt.py (the project you are posting this under)? xD

**Comment by Jumpin-JackFlash** [comment]
You obviously didn’t read it 🙄. Look instead of being rude, if you don’t want to answer about an example program for a QT_Py then don’t comment. But the comment clearly says for QT_Py.

**Comment by davidlatwe** [comment]
I assume this is your QT PY, https://github.com/adafruit/Adafruit-QT-Py-PCB
And this project is for the Python bindings of this Qt https://www.qt.io/

**Comment by Jumpin-JackFlash** [comment]
> I assume this is your QT PY, https://github.com/adafruit/Adafruit-QT-Py-PCB
> And this project is for the Python bindings of this Qt https://www.qt.io/

davidlatwe
This is the project link I am referring too. Like I mentioned I'm a NEWBIE so I may not being missing some steps.
I am running the latest version of Circuit Python 6.3 and loading the file with MU editor as the QT-Py suggest. This is the first sample project on ADAFruit https://learn.adafruit.com/adafruit-qt-py/circuitpython

https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/Welcome_to_CircuitPython/neopixel_blink.py

**Comment by davidlatwe** [comment]
Sorry mate, WRONG classroom for you to ask any question.

Perhaps you are not familiar with GitHub, so just want to make sure you know that, when you find a project that named like the one you are looking for, doesn't mean it serve for the same goal. And most of the project has a `README` page, please read it first before asking any question.

Lastly, NO ONE HERE working with ADAFruit NOR LED stuff.

You will NOT get anything you need here, not because we are being rude but you are in the wrong place.
