### ISSUE TITLE
QtCompat.isValid() Not Available for All Qt Objects

### ISSUE THREAD

**Issue by andryjong** [mottosso/Qt.py#369]
`QtCompat.isValid()` starts with the following `assert` statement:
https://github.com/mottosso/Qt.py/blob/242ec430ff390cf24051819802b9eec1e665d3b2/Qt.py#L816

However, not all objects in Qt inherits from `QObject` (e.g. `QGraphicsItem`, `QListWidgetItem`, `QTreeWidgetItem`, etc.). 
This `assert` statement makes `QtCompat.isValid()` not available for such objects.

How can I best check for object validity in this case?

**Comment by andryjong** [comment]
@mottosso -- Unfortunately, just like `QObject`, we cannot guarantee that an item is still in memory.

Casting `QGraphicsItem` into `QGraphicsObject` would work if the item itself is still valid.
Otherwise, we'll get into the same situation where it would say something like "Internal C++ object already deleted". 😭 

I've gotten around the `AssertionError` by having all of my items also inherit from `QObject`, like follows:
```python
class GroupItem(QtWidgets.QGraphicsItemGroup, QtCore.QObject)
```
... but this feels rather like a "hacky" way to get around the `assert` statement.

**Comment by mottosso** [comment]
Oh, is the problem only that there is an assert in Qt.py? Then it is surely safe to remove. I can't remember why this was put there. What kind of error should we expect shiboken to throw if an object does not support it? Should probably be fine? Something the user could catch?

If that's the only problem, then a PR removing this assert is more than OK.

**Comment by andryjong** [comment]
@mottosso -- Is there a time frame and/or process to get the latest version to PyPI?

**Comment by mottosso** [comment]
Sorry, I'm working on it. It's supposed to be automatic, but the build chain (Travis, or PyPI) has changed, apparently. If it doesn't work in the next 20 mins, then it'll be tomorrow.

**Comment by andryjong** [comment]
Understood. Thank you!! 🙏

**Comment by mottosso** [comment]
All done! 🥳

**Comment by andryjong** [comment]
Thank you so much, sir!
