### ISSUE TITLE
PyQt4 import should try and set sip api to v2

### ISSUE THREAD

**Issue by justinfx** [mottosso/Qt.py#37]
It would be good, for compatibility, for the PyQt4 import logic to also attempt to set the sip api version to 2 for at least QString and QVariant (setapi()). This will ensure that PyQt4 bindings behave the same way as PySide, when the helper library is hiding away the import details.

Caveat: It is possible for the setting of sip api v2 to fail, if another library was imported first, which uses PyQt4 and already locked sip into v1.

**Comment by fredrikaverpil** [comment]
[Here's](http://pyqt.sourceforge.net/Docs/PyQt4/incompatible_apis.html) what the docs say about it.

@mottosso I guess we could implement something like this inside of `_load_pyqt4()`:

```python
import sip
sip.setapi('QString', 2)
sip.setapi('QVariant', 2)

# Add
PyQt4.sip = sip
```

This would make it possible to perform something like this:

     from Qt import sip  # uses the v2 API

About the caveat, not sure if we can do anything about that?

**Comment by mottosso** [comment]
> @mottosso I guess we could implement something like this inside of _load_pyqt4():

Yes, that sounds like a good idea.

> About the caveat, not sure what/if we can do about that?

Not much, but we'll need to talk about what type of warning to throw, and possibly have a flag of sorts to choose between (1) throwing an exception or (2) simply log a message. It's possible that software built with API v1 might break under v2 and vice versa.

If you end up implementing this, try and think of a suitable test for it.

**Comment by fredrikaverpil** [comment]
@justinfx it would be useful to understand whether we should offer sip API v2 for only `QString` and `QVariant` or if we should provide the v2 for all those listed [here](http://pyqt.sourceforge.net/Docs/PyQt4/incompatible_apis.html). What do you think?

**Comment by fredrikaverpil** [comment]
@justinfx I've actually never gotten around using `QVariant` or `QString`. Are these PyQt4/PyQt5 specific and does not exist for PySide/PySide2?

To my knowledge, sip comes with PyQt4/PyQt5. It's unlikely that sip is available if you only have PySide installed, right?

To me it seems like that sip will only be available if you're have PyQt4/PyQt5 available. Therefore I'm wondering what should happen on a system which may only have PySide when you do this:

    from Qt import sip

Any suggestions?

**Comment by mottosso** [comment]
sip is the equivalent of shiboken and is specific to PyQt, but it shouldn't be part of its namespace. sip and shiboken both are standalone libraries. You could generate bindings for other C++ projects with them.

```python
import sip
import shiboken
```

If your system has them, then you could use them. I don't think they should have anything to do with Qt.py.

**Comment by fredrikaverpil** [comment]
> I don't think they should have anything to do with Qt.py.

You mean we shouldn't create some convenience function to set `sip` v2 API?

**Comment by mottosso** [comment]
> You mean we shouldn't create some convenience function to set sip v2 API?

I think we should force the use of the v2 API, and throw an error if it fails.

Here's what I see happening.

```python
def _pyqt4():
   ...
   import sip
   sip.setapi('QString', 2)
   sip.setapi('QVariant', 2)
   ...
```

Along with error handling. No need to add anything to the module I think.
