### ISSUE TITLE
Drop PyQt because it may be illegal to import a GPL lib from a lib under MIT

### ISSUE THREAD

**Issue by KOLANICH** [mottosso/Qt.py#373]
>PyQt5 is released under the GPL v3 license and under a commercial license that allows for the development of proprietary applications.

GPL is a viral license, the point of viral licenses is to infect everything. If one uses any GPL lib from a program/lib, that lib/program is legally required to be under GPL or AGPL, unless the copyright holder has given you a permission.

That's why this lib is mostly unneeded: PySide2 is already under a permissive license, PyQt cannot be used at all in permissively-licensed tools, and supporting both versions of PySide has a very minor benefit.

Suggestion: drop PyQt support as soon as possible.

**Comment by mottosso** [comment]
Thanks, we will take your advice under consideration.
