### ISSUE TITLE
QStringListModel not available in PySide2

### ISSUE THREAD

**Issue by johnsonthomasson** [mottosso/Qt.py#404]
Hi,

We are testing the latest code on `master` for use in both PySide2 and PySide6 contexts. I noticed that you temporarily released 1.4.0 but then took it down. So you may already be aware of this issue. 

At the moment we're finding, in a PySide2 context, `QStringListModel` is not available on `Qt.QtCore` or `Qt.QtGui`, however, it is available on `PySide2.QtCore`. In a PySide6 context, we're finding, as expected, `QStringListModel` is available on `Qt.QtCore`.

**Comment by mottosso** [comment]
Thanks for reporting this. 1.4.0 hasn't been released yet (unsure where you saw this?), you can follow the latest here and here.

- https://github.com/mottosso/Qt.py/pull/394
- https://github.com/mottosso/Qt.py/pull/403

Pushing a fix now.
