### ISSUE TITLE
QtGui.QGuiApplication

### ISSUE THREAD

**Issue by ZachGray** [mottosso/Qt.py#414]
Implemented Qt.py to port tools using Pyside2 to Maya 2025. 
QtGui.QGuiApplication was missing, I added to _common_members and it appeared to work. 

New to Qt.py, not sure if this is the correct implementation.

**Comment by mottosso** [comment]
This will work just fine, except it will break compatibility with PySide and PyQt4. See here for latest status on that: 

-  https://github.com/mottosso/Qt.py/issues/413
