### ISSUE TITLE
Possible PySide6-Enhancement:  Unlock Scoped Enums ( for instances ) <- Forgiveness-Mode

### ISSUE THREAD

**Issue by simsation** [mottosso/Qt.py#420]
Hi there ,  this is my first contribution - new to github , i hope it's alright :)

> i found out about "PYSIDE6_OPTION_PYTHON_ENUM" yesterday and did some tests  
> please see: https://doc.qt.io/qtforpython-6/developer/enumfeatures_doc.html

## 1. PySide6 - Unlock more Enum-Features

- In PySide6 the developers give us the possibility to unlock more Enum-Features
- setting some bits , one can enable ENOPT_SCOPED_SHORTCUT - which enables the old use of enums on instances  
- it seems to be quite easy to unlock , but has to be done "before" importing Qt , e.g.

```python:
import sys
sys.pyside6_option_python_enum = 13

from PySide6 import QtCore, QtGui, QtWidgets
```

> this will set to -->  ENOPT_NEW_ENUM | ENOPT_GLOBAL_SHORTCUT | ENOPT_SCOPED_SHORTCUT  
> with that set , following example will work , and not raise Errors anymore:  

```python:
font = QFont()
font.setWeight(Qt.Bold)
```

> the default value of os.environ('PYSIDE6_OPTION_PYTHON_ENUM') is 1 ( or better say "True" )  

## 2. turn off the forgiveness-mode:

- when setting the value 240 , one seems to be able to turn OFF completely OFF the forgiveness-mode  
- ( ENOPT_NO_FAKESHORTCUT | ENOPT_NO_FAKERENAMES | ENOPT_NO_ZERODEFAULT | ENOPT_NO_MISSING )
 
> that's when this example will not work anymore:  

```python:
layout = QVBoxLayout()
layout.setAlignment(Qt.AlignLeft)              # which works by default as part of ENOPT_GLOBAL_SHORTCUT 
# needs to become
layout.setAlignment(Qt.Alignment.AlignLeft)    # which seems to be the new recommended standard
```
### 2.1 current error in Qt.py
when setting to 240, Qt.py won't find the "shortcut" QtCore.Qt.MiddleButton:
- it will work , when changing Qt.py:
```python:
#     "MidButton": "QtCore.Qt.MiddleButton",
#     to
#     "MidButton": "QtCore.Qt.MouseButton.MiddleButton
```
### 2.2 why turn Forgiveness-Mode off ?  
> reason1: forward-thinking ( it could be the standard in later PySide-versions to come )  
> reason2: longnames , describe very precisely , for what operation each enum is meant for  
> reason3: checking compatibility with PyQt6  ( as there is no forgiveness-mode here )

```python:
# e.g. the pyside-developers recommended this construct for the future:  
# Qt.Monday       -->  Qt.DayOfWeek.Monday  
# Qt.blue         -->  Qt.GlobalColor.blue  
# Qt.Unchecked    -->  Qt.CheckState.Unchecked  
# Qt.AlignCenter  -->  Qt.AlignmentFlag.AlignCenter  
# QFont.DemiBold  -->  QFont.Weight.DemiBold
```

---
## 3. there is more Info on "Forgiveness-Mode" here
https://doc.qt.io/qtforpython-6/considerations.html#doing-a-smooth-transition-from-the-old-enums

- maybe some of you are struggling , with lots of tiny code-updates , concerning the enums - and this info might be of help for you , enabling the scoped_shortcuts

- maybe you want to implement this feature into Qt.py, it might be a nice PySide6-enhancement for Qt.py

- maybe one of you can do some tests , if this causes any issues, or if it is unusable for complex UIs

have a nice week
sim.On

**Comment by simsation** [comment]
oh sorry  -now i am disappointed,
 
seems like this only works in standalone-applications , 
i just tested it inside Maya , and i guess this value cannot be set , after maya has been started .

oh damn , seems my first post can be deleted again. lol

ok maybe it is interesting for someone , using PySide6 outside of maya , houdini , nuke

**Comment by mottosso** [comment]
Thanks for posting this here, and great investigatory work. Even if it did work post-Launch of Maya, Maya isn't the only place where Qt.py is used so it's important to take the general case in mind. But more importantly, one thing Qt.py cannot do is alter the behaviour of anything not-Qt.py. In this case, we would alter PySide6 too, which could/would break things that do not even use Qt.py.

So the solution, if one exists, must be confined to Qt.py and Qt.py alone.
