### ISSUE TITLE
latest Qt.py breaks model tester

### ISSUE THREAD

**Issue by p0las** [mottosso/Qt.py#422]
python 3.10. we used an older version (1.3.7) of qt.py. after updating to the latest (1.4.1) one we get tons of tests failing with this error:

```
self = <pytestqt.modeltest.ModelTester object at 0x000002202AE80D00>

    def _test_basic(self):
        """Try to call a number of the basic functions (not all).
    
        Make sure the model doesn't outright segfault, testing the functions
        which make sense.
        """
>       assert not self._model.buddy(qt_api.QtCore.QModelIndex()).isValid()
E       TypeError: 'PySide6.QtCore.QAbstractItemModel.buddy' called with wrong argument types:
E         PySide6.QtCore.QAbstractItemModel.buddy(QModelIndex)
E       Supported signatures:
E         PySide6.QtCore.QAbstractItemModel.buddy(typing.Union[PySide6.QtCore.QModelIndex, PySide6.QtCore.QPersistentModelIndex])
```

the only thing that changed is Qt.py. the attribute passed is correct and I do not understand why this is complaining.
posting here in case someone else had the same issue and have a solution.

**Comment by mottosso** [comment]
If you used 1.3.7, then you must also have used PySide2/PyQt5, as Qt 6 support was added in 1.4.1. This looks to be a PySide6 error, or more specifically an issue with the "model tester".

What is this "model tester"? Best Qt.py could do is provide a wrapper, but it would require this tester to use it.

**Comment by p0las** [comment]
yes we are still using PySide2/PyQt5 and we are getting ready for the new ones. I assumed that updating Qt.py would have no effect on the existing pipeline. I'm looking at the diff between the two versions and I see nothing that would explain the problem.
model tester is some automated pytest thing that tests models:
https://pytest-qt.readthedocs.io/en/latest/modeltester.html

**Comment by p0las** [comment]
the environment didn't change. the python/pyside/pyqt version are the same etc etc. the only change was update to qt.py
I also have errors in `qtbot`:
```>       with qtbot.waitSignal(thread.completed, timeout=9000) as blocker:
E       pytestqt.exceptions.TimeoutError: Signal  not emitted after 9000 ms
```
this indicates that pytest fixtures we had been using are no longer compatible with the 1.4.1

**Comment by mottosso** [comment]
But, this error is coming from PySide6?

```bash
E       TypeError: 'PySide6.QtCore.QAbstractItemModel.buddy' called with wrong argument types:
E         PySide6.QtCore.QAbstractItemModel.buddy(QModelIndex)
E       Supported signatures:
E         PySide6.QtCore.QAbstractItemModel.buddy(typing.Union[PySide6.QtCore.QModelIndex, PySide6.QtCore.QPersistentModelIndex])
```

Upgrading would have no effect on PySide2/PyQt5, can you confirm?

**Comment by p0las** [comment]
I think I see the issue. we have both pyside2 and pyside6 available and it seems that the updated Qt.py is picking up pyside6 while the older one was picking up pyside2 in the same environment. is there a way to specify priority if both are available?

**Comment by mottosso** [comment]
See https://github.com/mottosso/Qt.py?tab=readme-ov-file#override-preferred-choice

**Comment by p0las** [comment]
of course. sorry, long day. Thank you for your assistance and sorry to bug you. works perfectly.
