### ISSUE TITLE
Add similar projects to README

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#47]
- https://github.com/spyder-ide/qtpy/tree/master/qtpy
- https://github.com/jupyter/qtconsole/blob/master/qtconsole/qt_loaders.py

**Comment by mottosso** [comment]
This could have been a pull request.

**Comment by fredrikaverpil** [comment]
Sorry, yes. I made that as a mental note for later... as I was in the middle of https://github.com/mottosso/Qt.py/pull/41 ... but I'm adding it now.
