### ISSUE TITLE
Enforce portability?

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt.py#51]
Should Qt.py enforce/encourage portability? That is, should Qt.py try and *prevent* a user from using functionality found only in a specific binding, so that any code written with it is *guaranteed* to run on any other binding?

It's more or less a road in the fork between being a helper library or a complete framework.

**Scenario A - Yes portability**

```python
>>> from Qt import QtCore
>>> signal = QtCore.pyqtSignal()
AttributeError: 'module' object has no attribute 'pyqtSignal'
```

**Scenario B - No portability**

```python
>>> from Qt import QtCore
>>> signal = QtCore.pyqtSignal()
>>> signal2 = QtCore.Signal()
>>> from PyQt4 import QtCore
>>> signal3 = QtCore.pyqtSignal()
```

### Implementation

We could achieve this by simply removing the redirected members.

```python
PyQt4.QtCore.Signal = PyQt4.QtCore.pyqtSignal
del(PyQt4.QtCore.pyqtSignal)
```

However the problem is that this affects the PyQt4 module globally; meaning that if the user is running another application using PyQt4, it would break.

We could work around this by, rather than redirecting Qt.py to its nearest binding..

```python
>>> import Qt
>>> print(Qt)
<module 'PyQt4' from '/usr/lib/python2.7/dist-packages/PyQt4/__init__.pyc'>
```

..we re-define each member..

```python
>>> from Qt import QtCore
>>> print(QtCore)
<module 'Qt.QtCore' from '/usr/lib/python2.7/dist-packages/Qt.pyc'>
```

But the problem with that is (1) we would have to redefine every possible member of Qt which might be difficult and (2) because of (1) we would lose the current simplicity of Qt.py.

### Discussion

If we choose to enforce portability, we'll have to consider the consequences and find an elegant way in which to implement it. If we chose not to, we should consistently ensure that Qt.py can be used alongside any particular binding.

An alternative approach might be to instead have a separate tool check for used features only found in any one binding?

```python
# psuedo
# validate_portability.py
import PySide
import PyQt4

unique = set(all_pyside).intersect(set(all_pyqt4))

with open("mycode.py") as f:
  used_members = parse(f)
  for member in used_members:
    if member in unique:
      warn("%s is not portable!" % member)
```

**Comment by fredrikaverpil** [comment]
Hm. This is a tough one. What do you think?

With Qt.py, my ambition is to never have to import PySide or PyQt. I'll just use Qt.py. And I'll always code for PySide2 or PyQt5 and expect backwards compatibility to PySide2/PyQt4 (or some kind of convenience function like `load_ui` which takes different functions doing a similar thing and offering a way to avoid importing a binding next to Qt.py).

**Comment by fredrikaverpil** [comment]
Rather than

```python
>>> from Qt import QtCore
>>> signal = QtCore.pyqtSignal()
>>> signal2 = QtCore.Signal()
>>> from PyQt4 import QtCore
>>> signal3 = QtCore.pyqtSignal()
```

We could encourage:

```python
if Qt.__binding__.startswith('PyQt'):
    signal = QtCore.pyqtSignal()
elif Qt.__binding__.startswith('PySide'):
    signal = QtCore.Signal()
```

**Comment by fredrikaverpil** [comment]
I guess this can be closed?

**Comment by mottosso** [comment]
Yes, scenario B it is!
