### ISSUE TITLE
List of PyQt4 vs PySide incompatibilities

### ISSUE THREAD

**Issue by justinfx** [mottosso/Qt.py#65]
I have a very large PySide application that has been developed for over 3 years. I've just started to convert it from PySide to PyQt4 and am using Qt.py to see how well it handles it. Surprisingly, I am hitting quite a decent size list of incompatibilities, so I thought I would list them here. 

This list it not yet complete, asI have not finished fully testing every area of the app. I am a bit scared though, as Python is dynamic, that I could easily hit more of these during runtime if I don't manage to exercise every branch of the GUI code 

---

QtCore.Slot - PySide allows for a `result=None` keyword param to set the return type. PyQt4 crashes

```
    QtCore.Slot(QtGui.QWidget, result=None)
TypeError: string or ASCII unicode expected not 'NoneType'
```

---

QAction.triggered signal requires a bool arg in PyQt4, while PySide cannot accept any arguments

```python
# PySide
>>> a.triggered.emit()
>>> a.triggered.emit(True)
TypeError: triggered() only accept 0 arguments, 2 given!

# PyQt4
>>> a.triggered.emit()
TypeError: triggered(bool) has 1 argument(s) but 0 provided

>>> a.triggered.emit(True)  # is checked
```

---

QAbstractModel.createIndex(row, col, quint32)

In PySide, somehow the last argument (the id) is allowed to be negative and is maintained. While in PyQt4 it gets coerced into an undefined unsigned value.

```python

# PySide
>>> idx = model.createIndex(0, 0, -1)
>>> print idx.internalId()
# -1

# PyQt4
>>> idx = model.createIndex(0, 0, -1)
>>> print idx.internalId()
# 18446744073709551615
```

* Note - I had been using the id as an index into a list. But the unexpected return value from PyQt4 broke it by being invalid. The workaround was to always check that the returned id was between 0 and the max size I expect.

---

```python
# PySide
>>> QtGui.QItemSelection.empty()

# PyQt4
>>> QtGui.QItemSelection.isEmpty()
```

However, they both do support the len(selection) operation

---

Closures

```python 
# valid in PySide
def someMethod(self):
    def _wrapper():
        self.runSomething("foo")

    someObject._callback = _wrapper
    someObject.someSignal.connect(_wrapper)

# In PyQt4 an exception is generated when the signal fires
    def _wrapper():
        self.runSomething("foo")
NameError: free variable 'self' referenced before assignment in enclosing scope
```

---

In PySide, the constructor for `QtGui.QRegExpValidator()` can just take a `QRegExp` instance, and that is all.

In PyQt4 you are required to pass some form of a parent argument, otherwise you get a TypeError:

`QtGui.QRegExpValidator(regex, None)`
```

**Comment by justinfx** [comment]
If you would rather this ongoing list be managed in another format, let me know.

**Comment by mottosso** [comment]
Thanks a lot for this Justin, let's definitely keep these manageable.

As for a solution, I had this idea.

```python
QtCore.Slot = lambda widget: PyQt4.pyqtSlot(widget)
```

That is, installing a "weakest-link" type version of conflicting parameters, such that these errors appear loud and early.

One of the problem I encountered was with conflicting parameters on classes.

```python
# Bad
QtGui.QItemSelection.empty = QtGui.QItemSelection.isEmpty
```

For that, we could subclass things but at that point maybe it gets muddy fast?

Alternatively, we could keep a verbal list of gotchas, such as this one, and expect developers to test early and often. It would keep things simpler, but I wonder at what cost (or benefit as a helper library).

**Comment by justinfx** [comment]
I think its a good idea, like you said, to keep a really tidy list of all the known caveats. It would help to inform people writing from scratch, or to know what to debug for someone like me with tons of existing code. 

I guess if they are easy monkey patches, you could tackle some of them, since you are already doing it to an extend. But some things may just not be easy, like differences in constructors, unless you really wanna get crazy.

**Comment by mottosso** [comment]
> But some things may just not be easy, like differences in constructors, unless you really wanna get crazy.

I can see something like that easily getting way out of hand, but I'd be up for a separate branch. An anything-goes kind of branch, where we could test it out. I just don't want a million lines of brittle, repetitive code.

> to keep a really tidy list of all the known caveats

This is probably the best approach. I wonder how to best format such a list..

Maybe as a list of functions/classes/methods, each to a wiki page or section of the README with caveats?

- [QtCore.Slot](#QtCore.Slot)
- [QAction.triggered](#)
- [QAbstractModel.createIndex](#)
- [QtGui.QItemSelection.empty](#)
- [QtGui.QItemSelection.isEmpty](#)
- ...

Maybe they could each have a "tag" of sorts, indicating their severity.

- ![](http://gamestudiohx.com/wp-content/uploads/2013/07/warning_16.png) [QtCore.Slot](#)
- [QAction.triggered](#)
- [QAbstractModel.createIndex](#)
- ![](http://gamestudiohx.com/wp-content/uploads/2013/07/warning_16.png) [QtGui.QItemSelection.empty](#)
- ![](http://maps.gpsvisualizer.com/google_maps/icons/triangle/red.png) [QtGui.QItemSelection.isEmpty](#)

<br>
<br>

### [QtCore.Slot](#)

Notes about ...

### [QAction.triggered](#)

Notes about this one too..

And so on.

**Comment by justinfx** [comment]
That would work. I would probably look for stuff sorted by type name like
you first had it.

**Comment by fredrikaverpil** [comment]
What about using the wiki to document all of this?

**Comment by mottosso** [comment]
The wiki might make sense, but what I like about the README is the pull request potential. It also stays connected to the version of Qt.py, whereas the Wiki might show newer information than what is currently available in the version someone happens to use. It won't matter much at the moment, as there aren't that many versions, but once versions start differing, it can more get difficult to manage.

If not in the README.md, then how about a separate GOTCHAS.md or something like it? I'm also cautious not to split information into too many places. I'd rather have a huge README that contains all you need to know.

**Comment by fredrikaverpil** [comment]
> pull request potential

That makes a whole lot of sense.

> If not in the README.md, then how about a separate GOTCHAS.md or something like it?

Ah, that's a really good idea. I like that!
I'm can't come up with a really good name for it ... perhaps we could call it COMPATIBILITY.md or DISCREPANCIES.md. Hm...

> I'm also cautious not to split information into too many places. I'd rather have a huge README that contains all you need to know.

I agree in general with you, but I think in this case that the GOTCHAS could become quite huge. Therefore I would like to cast my vote to put this in a separate file and prominently link it from the README.

**Comment by mottosso** [comment]
>  but I think in this case that the GOTCHAS could become quite huge.

I think you're right. Feel free to submit a pull request.

**Comment by fredrikaverpil** [comment]
@justinfx thanks for these caveats!

I'm closing this issue now and we can keep document things like these in the new [`CAVEATS.md`](https://github.com/mottosso/Qt.py/blob/master/CAVEATS.md).

**Comment by justinfx** [comment]
Cool. Thanks for formatting this!
