### ISSUE TITLE
Support alternate install locations / import paths of Qt module

### ISSUE THREAD

**Issue by justinfx** [mottosso/Qt.py#66]
`Qt.py` wants to replace itself with the resolved Qt bindings, by updating `sys.modules`. But it uses a hard-coded "Qt" string instead of `__name__`. This causes it not to work in my case where I am currently vendoring the `Qt.py` dependency into my project.

My import path looks something like this:

```python
from project.packages import Qt
```

I had to update the locations that did this:

```python
sys.modules["Qt"] = available[preferred]()
```

With

```python
sys.modules["Qt"] = available[preferred]()
sys.modules[__name__] = sys.modules["Qt"]
```

**Comment by mottosso** [comment]
Ah, interesting. I'm vendoring too, and did this, which works fine.

```python
from .vendor import Qt
from Qt import QtWidgets, QtGui
```

- [Link](https://github.com/pyblish/pyblish-lite/blob/c1e9bf571174619bd0e60642c28d0e91097e5ebb/pyblish_lite/app.py#L5)

Are you saying that if we make this change, we could do this?

```python
from .vendor.Qt import QtWidgets, QtGui
```

**Comment by justinfx** [comment]
Ah yep. That's the difference. If you apply the proposed fix, you can then import the contents transparently. 

In my case I was using absolute import paths, which shouldn't make a difference, but I was trying to do:
```python
from project.packages.Qt import QtCore, QtGui
```

**Comment by mottosso** [comment]
Ah, that's excellent. Could you make a PR for this?
