### ISSUE TITLE
Remaps: QItemSelection, QItemSelectionModel

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#68]
I'm finishing up some stuff and just quickly jotting this down so I can adress this later on...

**QItemSelection**
- PyQt4: [QtGui.QItemSelection](http://pyqt.sourceforge.net/Docs/PyQt4/qitemselection.html)
- PySide: [QtGui.QItemSelection](https://srinikom.github.io/pyside-docs/PySide/QtGui/QItemSelection.html)
- PyQt5: [QtCore.QItemSelection](http://pyqt.sourceforge.net/Docs/PyQt5/api/qitemselection.html)
- PySide2: where are the docs?
- Qt5: [QtCore.QItemSelection](http://doc.qt.io/qt-5/qitemselection.html)

**QItemSelectionModel**
- PyQt4: [QtGui.QItemSelectionModel](http://pyqt.sourceforge.net/Docs/PyQt4/qitemselectionmodel.html)
- PySide: [QtGui.QItemSelectionModel](https://srinikom.github.io/pyside-docs/PySide/QtGui/QItemSelectionModel.html)
- PyQt5: [QtCore.QItemSelectionModel](http://pyqt.sourceforge.net/Docs/PyQt5/api/qitemselectionmodel.html)
- PySide2: where are the docs?
- Qt5: [QtCore.QItemSelectionModel](http://doc.qt.io/qt-5/qitemselectionmodel.html)

So it seems we should be able to do:

```python
def _pyqt4():
    # Remap
    PyQt4.QtCore.QItemSelection = PyQt4.QtGui.QItemSelection
    PyQt4.QtCore.QItemSelectionModel = PyQt4.QtGui.QItemSelectionModel

def _pyside():
    # Remap
    PySide.QtCore.QItemSelection = PySide.QtGui.QItemSelection
    PySide.QtCore.QItemSelectionModel = PySide.QtGui.QItemSelectionModel
```

**Comment by eoyilmaz** [comment]
Hey Fredrik,

I keep finding your stuff all over the internet while switching to Maya 2017 and PySide2 :)

Cheers,

**Comment by fredrikaverpil** [comment]
Hi Erkan :)
There's more work than usual with Maya 2017. Within a few weeks I'll put the new Render Setup to the test and I plan to write some about my findings on that too.
