### ISSUE TITLE
Exclude bindings from lookup

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt.py#76]
### Goal

Enable the end-user to exclude specific bindings from being made available, even though they are on PYTHONPATH.

### Motivation

In some circumstances, only some bindings can reasonable be expected to exist. For example, in Autodesk Maya, only bindings for Qt 4 are possible and attempting to use Qt 5 may cause a crash.

### Implementation

Alongside `QT_PREFERRED_BINDING` we'll make a `QT_EXCLUDE_BINDING`.

```bash
$ export QT_EXCLUDE_BINDING=PySide2:PyQt5
```

Question is whether to make it plural, as it's mean for multiple values, or singular to align with the other environment variable. Which is easier to remember, and which is easier understood?

**Comment by fredrikaverpil** [comment]
Doesn't matter to me. I think your suggestion looks fine. As long as the README says you can define multiple bindings, we're good.

**Comment by fredrikaverpil** [comment]
This is a good idea, by the way :)
I currently force the default binding in e.g. Maya and Nuke. I'd rather exclude bindings.

**Comment by mottosso** [comment]
Maybe that's the better way, to set multiple ones using the preferred variable.

```python
$ export QT_PREFERRED_BINDING=PySide:PyQT4
```

Yeah, I think that makes a lot of sense. And no more variables to manage. What do you think?

**Comment by fredrikaverpil** [comment]
Yeah, that works for me.

**Comment by fredrikaverpil** [comment]
From your commit:
> `os.pathsep`

Will this mean you use a semicolon in Windows?
