### ISSUE TITLE
Add support for additional arguments to load_ui

### ISSUE THREAD

**Issue by bpabel** [mottosso/Qt.py#80]
Per the python mailing list discussion, add support for the 2nd argument to uic.loadUi

Here is an example using PyQt4

http://nullege.com/codes/search/PyQt4.uic.loadUi

Here is an example of an implementation for PySide that accepts the same arguments

https://gist.github.com/cpbotha/1b42a20c8f3eb9bb7cb8

**Comment by mottosso** [comment]
Thanks @bpabel.

> Per the python mailing list discussion

Would it be possible to link to this discussion?

> Here is an example of an implementation for PySide that accepts the same arguments

Excellent, would you happen to know whether the same implementation works for PySide2? If you put a pull-request in, we could have it run through tests on each platform, Python version and Qt distribution. That should get the conversation started.

As I'm not a user of loadUi myself, it would also be lovely to have one or more usage examples so that we implement it in a way that makes sense to you.

**Comment by fredrikaverpil** [comment]
> Would it be possible to link to this discussion?

This was from the 3DPRO mailing list. I asked Abel to post an issue :)
@mottosso Did you get my invite?

> Excellent, would you happen to know whether the same implementation works for PySide2?

I've made a gist where this works in PySide2:
https://gist.github.com/fredrikaverpil/0a89b174c9d29bc585f11d250adf2a7c

I think Abel's request makes a lot of sense. I omitted additional arguments to the `load_ui` convenience function but here's a clear way to support that. We should do it!

**Comment by mottosso** [comment]
Would it be possible to post a minimal example `ui` file, along with how it is used today, and how you would like it to be used with this feature?

**Comment by fredrikaverpil** [comment]
> Would it be possible to post a minimal example ui file, along with how it is used today, and how you would like it to be used with this feature?

I could do a PR, but I won't have time for it until mid August 😢 as I'm on vacation with my family.

However, [here's](https://github.com/fredrikaverpil/pyvfx-boilerplate/blob/master/boilerdata/main_window.ui) an example UI file. Today, we can access the widgets from the ui file like this:

# Load UI
self.main_widget = load_ui(main_window_file)

# Edit widget which resides in main window UI
self.main_widget.boilerPushButton.setText('Push me!')

However, we can't load the UI into `self` and make the pushButton available like so: `self.boilerPushButton`. So let's say you load three UI files and want all of their widgets to be accessed like `self.widgetName`. Today this is possible in PyQt but not in PySide (without `pysideuic`). But with @bpabel's gist, this seems doable with a custom `QUiLoader` class.

@mottosso if you like, we can assign this to me, but I won't have time for it until a couple of weeks away.

**Comment by fredrikaverpil** [comment]
Sorry, I edited my prevous post a lot. Please re-read it if you already read it 😜

**Comment by fredrikaverpil** [comment]
If we were to write tests for this, we'd need to store a .ui file in the repository. How do you feel about that, @mottosso ?

We could create a main_window.ui file in a `data` dir?

**Comment by mottosso** [comment]
We could, but I'd rather keep it contained in the test module.

If you hand me a .ui snippet, I can show you how I mean.

**Comment by fredrikaverpil** [comment]
> If you hand me a .ui snippet, I can show you how I mean.

Will this do?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>MainWindow</class>
 <widget class="QMainWindow" name="MainWindow">
  <property name="windowTitle">
   <string>MainWindow</string>
  </property>
  <widget class="QWidget" name="centralwidget">
   <layout class="QGridLayout" name="gridLayout">
    <item row="0" column="0">
     <widget class="QPushButton" name="pushButton">
      <property name="text">
       <string>PushButton</string>
      </property>
     </widget>
    </item>
   </layout>
  </widget>
  <widget class="QMenuBar" name="menubar">
   <property name="geometry">
    <rect>
     <x>0</x>
     <y>0</y>
     <width>125</width>
     <height>22</height>
    </rect>
   </property>
  </widget>
  <widget class="QStatusBar" name="statusbar"/>
 </widget>
 <resources/>
 <connections/>
</ui>
```

**Comment by mottosso** [comment]
Here's what I had in mind.

```python
def test_pyside_load_ui():
    """load_ui works well"""

    ui = """\
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>MainWindow</class>
 <widget class="QMainWindow" name="MainWindow">
  <property name="windowTitle">
   <string>MainWindow</string>
  </property>
  <widget class="QWidget" name="centralwidget">
   <layout class="QGridLayout" name="gridLayout">
    <item row="0" column="0">
     <widget class="QPushButton" name="pushButton">
      <property name="text">
       <string>PushButton</string>
      </property>
     </widget>
    </item>
   </layout>
  </widget>
  <widget class="QMenuBar" name="menubar">
   <property name="geometry">
    <rect>
     <x>0</x>
     <y>0</y>
     <width>125</width>
     <height>22</height>
    </rect>
   </property>
  </widget>
  <widget class="QStatusBar" name="statusbar"/>
 </widget>
 <resources/>
 <connections/>
</ui>"""
    
    with tempfile.NamedTemporaryFile(suffix=".ui") as f:
        f.write(ui)
        f.seek(0)

        with pyside():
            import Qt
            widget = Qt.load_ui(f.name)

```

Ideally then, the .ui file would only contain parts we are actually testing. In this case, perhaps QStatusBar and explicit widths are less important in the interest of readability.

**Comment by fredrikaverpil** [comment]
Ah, yes. That's an excellent idea.

**Comment by mottosso** [comment]
It might not seem like a big deal today. From [experience with maintaining external files with tests](https://github.com/pyblish/pyblish-base/tree/master/tests/pre11/plugins), I find that this works fine initially, but then as the project is updated, tests change, and the external files will need to branch out to cover both in order to be backwards compatible.

With this approach, even though it makes each test bigger and more repetitive, tests and data change together and should be easier to maintain long-term.

**Comment by fredrikaverpil** [comment]
Yep. Agreed.

**Comment by fredrikaverpil** [comment]
Hm, so I'm wondering about one thing. It looks like we could add a custom class to the `_pyside` and `_pyside2` functions. First, it's quite unconventional to define a class inside a function, but it will inherit `QtUiTools.QUiLoader` from PySide/PySide2 and will throw an error if Qt.py is using PyQt4/PyQt5.

Right now, I'm just putting the class definition in both these functions. Any idea on how we could structure this more nicely?

**Comment by fredrikaverpil** [comment]
Never mind, I think I found a solution.

**Comment by mottosso** [comment]
@fredrikaverpil If you can, please post an example or two of the intended usage before looking at implementing this.

What I'm looking for is to have tests in place before the implementation starts. TDD style.

**Comment by fredrikaverpil** [comment]
Yes, I'm doing the tests now. But as I had to rebuild the docker container I now am having issues with nosetests complaining about not being able to connect to an X server:

```
...
...
Raise ImportError if sip API v1 was already set (Python 2.x only) ... ok
load_ui works well ... ERROR
nosetests: cannot connect to X server
```

Do you see this on your end too?

**Comment by mottosso** [comment]
See #81
