### ISSUE TITLE
QSortFilterProxyModel can't be imported

### ISSUE THREAD

**Issue by hdd** [mottosso/Qt.py#86]
Hi Marcus, trying now to port some complex stuff on Qt.py,  but started hitting some issues:

``` python
from Qt.QtGui import QSortFilterProxyModel
ImportError: cannot import name QSortFilterProxyModel
```

any idea ?
Cheers.

p.s

``` python
from PySide.QtGui import QSortFilterProxyModel
print QSortFilterProxyModel
>> <type 'PySide.QtGui.QSortFilterProxyModel'>
```
``` python
print Qt
<module 'PyQt5' from '/usr/lib64/python2.7/site-packages/PyQt5/__init__.pyc'>
```

I'll try forcing on PySide

**Comment by mottosso** [comment]
Hey @hdd, thanks for this. Looks like a bug. I'll have a PR ready in the new few mins.

**Comment by mottosso** [comment]
Note that this class should be accessed via QtCore.

- https://doc.qt.io/qt-5/qsortfilterproxymodel.html

**Comment by mottosso** [comment]
Arriving on PyPI in a few minutes.

- https://travis-ci.org/mottosso/Qt.py/jobs/149454277

**Comment by hdd** [comment]
Thanks man, really is appreciated!
I'll give it a whirl as soon as it land.
