### ISSUE TITLE
load_ui example in README could be better

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt.py#89]
The guide [here](https://github.com/mottosso/Qt.py#load-qt-designer-ui-files) has a spelling error and more importantly provides an example that could be improved.

 ```python
import sys
from Qt import QtWidgets
from Qt import load_ui


class Hello(QtWidgets.QWidget):
    def __init__(self):
        super(Hello, self).__init__()
        self.ui = load_ui('my_ui.ui')

app = QtWidgets.QApplication(sys.argv)
window = Hello()
window.ui.show()

sys.exit(app.exec_())
```

This could have been:

```python
import sys
import Qt

app = QtWidgets.QApplication(sys.argv)
ui = Qt.load_ui("my.ui")
ui.show()
app.exec_()
```

Loading a standalone widget to the inside of another standalone widget doesn't make much sense to me.

**Comment by fredrikaverpil** [comment]
Yes, I agree. let's change it to match your suggestion. It looks much cleaner/simpler and it is to the point.

You could have one .ui file which serves as your `QMainWindow`, and then several .ui files which inherit a `QWidget` which may act as "modules" (not Python modules) within your main window (example, image browser where each thumbnail is one widget made out of a .ui file). But even then, the existing `load_ui` example isn't explaining that.
