### ISSUE TITLE
Qt py in maya 2017

### ISSUE THREAD

**Issue by hdd** [mottosso/Qt.py#92]
Hi, I've been reading this article : 
https://fredrikaverpil.github.io/2016/07/25/dealing-with-maya-2017-and-pyside2/

but when I try to import Qt into maya 2017 I get straight a : 

```
File "....../site-packages/Qt.py", line 234, in _init
    raise ImportError("No Qt binding were found.")
````
do I have to set manually to PySide2 ? 
should be able to automatically try them all and import ?
Am I missing something ? :)

Cheers.
L.

ps.
Note, PySide2 is available:

```
<module 'PySide2' from '/usr/autodesk/maya2017/lib/python2.7/site-packages/PySide2/__init__.py'>

```

**Comment by hdd** [comment]
trying the same code on 2016  (PySide) load without any issue.

**Comment by fredrikaverpil** [comment]
Hm, that's strange. To understand your case better, how do you make Qt.py available to Maya 2017?

**Comment by fredrikaverpil** [comment]
By the way, if you set `QT_PREFERRED_BINDING=PySide` and then attempt to run `import Qt` you'll get that error since your preferred binding isn't found.

Perhaps that error should be changed into "Qt could not find the preferred binding(s)" when this is the case.

**Comment by mottosso** [comment]
Ah, that could be a potential cause.

You can enable debugging of what it tries to do with the QT_VERBOSE environment variable. Set it to anything, and it should print which bindings it tries.

**Comment by hdd** [comment]
@fredrikaverpil Qt.py is simply available at maya startup time into PYTHONPATH
@mottosso I'll run some debugs today and report.
Cheers.

**Comment by hdd** [comment]
Sorry got this sorted.
was quite easy to get this sorted with :

```
os.environ['QT_PREFERRED_BINDING'] = 'PySide:PySide2'
```

Nice feature btw!
Cheers.

**Comment by fredrikaverpil** [comment]
I'm glad you got it sorted. 😄

**Comment by mottosso** [comment]
Oh, but you shouldn't need to do that. Did you figure out why it happened in the first place? Did you have  PyQt5 available at the same time? Would love to patch it up.

**Comment by fredrikaverpil** [comment]
This is on OS X:

```bash
export PYTHONPATH=$(pwd)
echo $pwd
/Users/fredrik/code/repos/Qt.py
/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/Maya
```

In Maya:

```python
>>> from Qt import __binding__
>>> print(__binding__)
PySide2
```

**Comment by hdd** [comment]
I have a startup ui (PySide) , which spawn maya (PySide2), therefore I've got to force this order of resolution so the right bindings are available in the correct order. 

Speaking of which , doesn't seem there's a default resolution order in place ?
Wondering whether this should be looking first at the new binding or the other way round....
eg : PySide2:PyQt5:PySide:PyQt4 VS PyQt4:PySide:PyQt5:PySide2

Thoughts ?

**Comment by mottosso** [comment]
> therefore I've got to force this order of resolution so the right bindings are available in the correct order.

That's perfectly reasonable I think. For Maya, one should set the preferred order as well, to not include Qt 4 on Maya 2017 and above, and vice versa for prior versions, so as to not accidentally import the wrong one if available.

> Speaking of which , doesn't seem there's a default resolution order in place ?

Default order is [here](https://github.com/mottosso/Qt.py/blob/a28322c9994f50c0f3c81d26abb52ba31cd78b3c/Qt.py#L210).

Maybe it should be more prominent in the README. Would you like it to appear in some other way? In an environment variable?

**Comment by mottosso** [comment]
Considering this solved!

**Comment by Skytale** [comment]
Guys, trying vfx-boilerplace code with old and updated Qt.py - getting exactly the same issue.
Any idea on what to do?

**Comment by mottosso** [comment]
Hi @Skytale,

Which version of Qt.py are you running?

You can view it in the file itself, for example [here](https://github.com/mottosso/Qt.py/blob/227f4df23e55323de86738148782c29f93c50ea4/Qt.py#L66).

**Comment by mottosso** [comment]
Judging by your output, it looks like you may have set the Preferred Binding to only look for PySide, which isn't available to Maya 2017.

Have you tried the solution posted by @hdd? You may need to expose PySide 2.
