### ISSUE TITLE
QWebKit remapping

### ISSUE THREAD

**Issue by hdd** [mottosso/Qt.py#94]
It seems in Qt5 webkit has been reshuffled as well as QtGui.
This means that QWebPage is no longer available under QtWebKit , but is now under QtWebKitWidgets.

PySide
```python
From Qt.QtWebkit import QWebPage
```

PySide2
```python
From Qt.QtWebKitWidgets import QWebPage
```

I'll createa branch with this fix and open a pull request.

L.

**Comment by hdd** [comment]
here you go : https://github.com/mottosso/Qt.py/pull/95

**Comment by mottosso** [comment]
Merged!
