### ISSUE TITLE
QCoreApplication::UnicodeUTF8 is deprecated

### ISSUE THREAD

**Issue by hdd** [mottosso/Qt.py#98]
Found this :https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5
about this issue.

This gets raised, when trying to use compiled widget (pyside-uic....), which has the retranslateUi() .

``` PySide
QApplication::translate("Href_Gui", "Text:", 0, QApplication::UnicodeUTF8)
```

```PySide2
QApplication::translate("Href_Gui", "Text:", 0)
```

Not really sure how to tackle this down.

**Comment by hdd** [comment]
guess we can implement a mocked QApplication.UnicodeUTF8 property
and provide an override for PySide2/Qt5 on translate, so they can accept an argument more.

Thoughts ?

**Comment by hdd** [comment]
I've been opening a pull request : https://github.com/mottosso/Qt.py/pull/99

**Comment by mottosso** [comment]
Sorry to ask, but is this a problem you need solved? Or are you trying to cover all incompatibilities?

**Comment by hdd** [comment]
I'm porting a quite complex stack of code over Qt.py and it was using compiled ui ( designer-qt4 ) through pyside-uic code, which by default sneak in the translate function.

Without this fix, any interface build with PySide/PyQt won't simply be loading, and error, and possibly make the app segfault.

**Comment by mottosso** [comment]
Ah, excellent.

An example in the form of a test would be lovely to really drive this feature home.

**Comment by hdd** [comment]
thought the same, but I need #93 first .
So we can test both.

**Comment by mottosso** [comment]
#93 implemented.

**Comment by hdd** [comment]
tests are now available

**Comment by mottosso** [comment]
For completeness, the missing piece of information is an example that illustrates the problem.

**Comment by mottosso** [comment]
Implemented in [0.5.0](https://github.com/mottosso/Qt.py/releases/tag/0.4.0).

@hdd, let me know how this works for you!

**Comment by hdd** [comment]
Hi Marcus, 
Does this solve also the UnicodeUTF8 Remapping issue on QApplication ?
(as it can't simply be ignored on old PyQt4/PySide code)

**Comment by mottosso** [comment]
Hey @hdd,

It solves it by compiling your .ui files with PySide2. That compiler won't produce references to this member.

**Comment by mottosso** [comment]
For completeness, the solution is to compile with PySide2-compatible compiler, and then either replace references to `PySide2` with `Qt`, or automatically do so with `--compile`. See the [release](https://github.com/mottosso/Qt.py/releases/tag/0.5.0) for details.
